# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 16
# job:        ecc405f020bd  (https://refugio-hackathon-nine.vercel.app/jobs/ecc405f020bd)
# deliveries: 24    points: 0    runtime: 0.5s
# submitted:  2026-06-27 10:06:49.794 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/ecc405f020bd    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0024__equipo-16__ecc405f020bd.py --count 20
# ===========================================================================

"""REFUGIO Warehouse Challenge — simple, correct reference submission.

Two required entry points (loaded by warehouse.submission_loader):

  * create_layout() -> dict   : the static 960-shelf warehouse map
  * act(observation) -> Action: one action for one robot on one tick

The policy is pure and stateless: every decision is a function of the single
Observation it is handed. We import the stable public types from ``warehouse_api``
(exactly as the starter-kit examples do) so action values, the grid encoding,
and observation field names all match the simulator.

Strategy, kept deliberately simple:
  * Layout: the canonical "wide avenue" warehouse — 2-wide shelf columns with
    2-wide aisles between them, in four horizontal bands separated by 2-wide
    cross-aisles. This passes every layout constraint (exactly 960 shelves,
    each with an adjacent pickup cell, no blocked base entries, one connected
    walkable region) and the width-2 avenues give 96 robots room to pass.
  * Policy: greedy Manhattan navigation toward the goal (a free cell next to the
    target shelf when empty-handed; the base drop cell when carrying), avoiding
    shelves and cells currently occupied by other robots. PICKUP/DROP fire the
    moment the robot is in position. A tick/id-based tie-break and a sideways
    "escape" step keep symmetric robots from livelocking in the aisles.
"""

from __future__ import annotations

from warehouse_api import Action, CellType, Observation, Position


# ---------------------------------------------------------------------------
# Layout
# ---------------------------------------------------------------------------

# Wide-avenue shelf blocks: 2-wide shelf columns starting every 4 cells (so a
# 2-wide aisle sits between each pair), grouped into four 10-row bands with
# 2-wide cross-aisles between them. This yields exactly 12 * 2 * 4 * 10 = 960.
_SHELF_COLUMN_STARTS = range(3, 48, 4)
_SHELF_ROW_BANDS = ((3, 12), (15, 24), (27, 36), (39, 48))


def create_layout() -> dict:
    """Return the static warehouse layout: {"schema_version": 1, "shelves": [...]}."""
    shelves: list[list[int]] = []
    for x0 in _SHELF_COLUMN_STARTS:
        for y0, y1 in _SHELF_ROW_BANDS:
            for x in (x0, x0 + 1):
                for y in range(y0, y1 + 1):
                    shelves.append([x, y])
    return {"schema_version": 1, "shelves": shelves}


# ---------------------------------------------------------------------------
# Policy
# ---------------------------------------------------------------------------

# (dx, dy) -> movement action. Matches the simulator's MOVE_DELTAS exactly:
# UP decreases y, DOWN increases y, LEFT decreases x, RIGHT increases x.
_DELTA_TO_ACTION: dict[Position, Action] = {
    (0, -1): Action.UP,
    (0, 1): Action.DOWN,
    (-1, 0): Action.LEFT,
    (1, 0): Action.RIGHT,
}


def act(observation: Observation) -> Action:
    """Return exactly one action for this robot on this tick (pure, stateless)."""
    pos = observation.position

    if observation.carrying_item:
        goal = _drop_cell_for_base(observation.base_position)
        if pos == goal:
            return Action.DROP
        return _greedy_step(observation, goal)

    # Empty-handed: grab the target shelf the moment we're beside it.
    if _adjacent(pos, observation.target_item_position):
        return Action.PICKUP

    goal = _nearest_pickup_cell(observation)
    if goal is None:
        return Action.WAIT
    return _greedy_step(observation, goal)


def _adjacent(a: Position, b: Position) -> bool:
    return abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1


def _drop_cell_for_base(base: Position) -> Position:
    """The unique walkable interior cell adjacent to an external base."""
    x, y = base
    if y == 0:
        return (x, 1)
    if y == 51:
        return (x, 50)
    if x == 0:
        return (1, y)
    return (50, y)


def _is_empty(observation: Observation, cell: Position) -> bool:
    x, y = cell
    grid = observation.grid
    return (
        0 <= y < len(grid)
        and 0 <= x < len(grid[y])
        and grid[y][x] == CellType.EMPTY
    )


def _nearest_pickup_cell(observation: Observation) -> Position | None:
    """Closest free cell orthogonally adjacent to our target shelf."""
    tx, ty = observation.target_item_position
    candidates = ((tx + 1, ty), (tx - 1, ty), (tx, ty + 1), (tx, ty - 1))
    free = [cell for cell in candidates if _is_empty(observation, cell)]
    if not free:
        return None
    px, py = observation.position
    return min(
        free,
        key=lambda c: (abs(px - c[0]) + abs(py - c[1]), c[1], c[0]),
    )


def _greedy_step(observation: Observation, goal: Position) -> Action:
    """Step toward goal, avoiding shelves and currently-occupied cells.

    Movement resolves simultaneously, so refusing to enter an occupied cell is
    conservative but never causes a collision. We try the two distance-reducing
    moves (longer axis first); if both are blocked we WAIT — holding the lane
    beats wandering sideways, which just re-congests the aisles.
    """
    x, y = observation.position
    gx, gy = goal
    occupied = set(observation.all_robot_positions.values())

    dx = (gx > x) - (gx < x)
    dy = (gy > y) - (gy < y)

    horiz = (dx, 0)
    vert = (0, dy)
    progress = [horiz, vert]

    for mx, my in progress:
        if mx == 0 and my == 0:
            continue
        nxt = (x + mx, y + my)
        if nxt in occupied or not _is_empty(observation, nxt):
            continue
        return _DELTA_TO_ACTION[(mx, my)]

    return Action.WAIT
