# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 11
# job:        b2c1f8fc5722  (https://refugio-hackathon-nine.vercel.app/jobs/b2c1f8fc5722)
# deliveries: 97    points: 0    runtime: 1.11s
# submitted:  2026-06-27 10:09:15.276 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/b2c1f8fc5722    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0097__equipo-11__b2c1f8fc5722.py --count 20
# ===========================================================================

"""REFUGIO Warehouse Challenge submission.

Strategy:
- Layout: vertical shelf strips (2 cells wide) separated by wide aisles so robots
  can route around each other instead of deadlocking in 2-cell corridors.
- Policy: BFS distance fields cached per goal cell over the static obstacle grid
  (shelves + boundary never change during a run), so per-tick routing is a cheap
  table lookup. A per-tick cell reservation pass (lower robot_id reserves first,
  matching collision priority) avoids vertex conflicts and edge swaps.

Only `warehouse_api` and the stdlib are used.
"""

from __future__ import annotations

from collections import deque

from warehouse_api import Action, CellType, Observation, Position


# --- Layout ---------------------------------------------------------------

# Walkable interior is [1..50] x [1..50]. Shelves are placed as 2-wide columns
# grouped into 4 horizontal bands, with 2-cell cross-aisles between bands and
# 2-cell aisles between columns. This keeps every shelf close to an aisle from
# multiple sides (short detours) while staying one connected floor.
#
# 12 column-starts x 2 cols x 4 bands x 10 rows = 960 shelves.
_SHELF_COLUMN_STARTS: tuple[int, ...] = tuple(range(3, 48, 4))
_SHELF_ROW_BANDS: tuple[tuple[int, int], ...] = ((3, 12), (15, 24), (27, 36), (39, 48))


def create_layout() -> dict[str, object]:
    shelves: list[list[int]] = []
    for x0 in _SHELF_COLUMN_STARTS:
        for y0, y1 in _SHELF_ROW_BANDS:
            for x in (x0, x0 + 1):
                for y in range(y0, y1 + 1):
                    shelves.append([x, y])
    return {"schema_version": 1, "shelves": shelves}


# --- Policy state (module-level caches) -----------------------------------

_GRID_SIG: tuple[int, int] | None = None  # (height, width) of cached grid
_WALKABLE: frozenset[Position] = frozenset()
_DIST_CACHE: dict[Position, dict[Position, int]] = {}

# Per-tick reservation of destination cells, shared across robots in one tick.
_RES_TICK: int = -1
_RESERVED: set[Position] = set()
_RES_FROM: dict[Position, Position] = {}  # reserved cell -> robot's origin cell

_DELTAS: tuple[tuple[Action, int, int], ...] = (
    (Action.RIGHT, 1, 0),
    (Action.LEFT, -1, 0),
    (Action.DOWN, 0, 1),
    (Action.UP, 0, -1),
)


def _build_walkable(grid: tuple[tuple[CellType, ...], ...]) -> None:
    global _GRID_SIG, _WALKABLE, _DIST_CACHE
    cells: set[Position] = set()
    for y, row in enumerate(grid):
        for x, cell in enumerate(row):
            if cell == CellType.EMPTY:
                cells.add((x, y))
    _WALKABLE = frozenset(cells)
    _GRID_SIG = (len(grid), len(grid[0]) if grid else 0)
    _DIST_CACHE = {}


def _dist_field(goal: Position) -> dict[Position, int]:
    """BFS distances from every walkable cell to `goal` (cached, static grid)."""
    cached = _DIST_CACHE.get(goal)
    if cached is not None:
        return cached
    dist: dict[Position, int] = {}
    if goal not in _WALKABLE:
        # Goal sits on a shelf/border (e.g. a target item). Seed BFS from its
        # walkable neighbours so robots route to an adjacent pickup cell.
        frontier: deque[Position] = deque()
        gx, gy = goal
        for _a, dx, dy in _DELTAS:
            n = (gx + dx, gy + dy)
            if n in _WALKABLE:
                dist[n] = 1
                frontier.append(n)
    else:
        dist[goal] = 0
        frontier = deque([goal])
    while frontier:
        cx, cy = frontier.popleft()
        d = dist[(cx, cy)]
        for _a, dx, dy in _DELTAS:
            n = (cx + dx, cy + dy)
            if n in _WALKABLE and n not in dist:
                dist[n] = d + 1
                frontier.append(n)
    _DIST_CACHE[goal] = dist
    return dist


def _drop_cell_for_base(base: Position) -> Position:
    x, y = base
    if y == 0:
        return (x, 1)
    if y == 51:
        return (x, 50)
    if x == 0:
        return (1, y)
    return (50, y)


def _adjacent(a: Position, b: Position) -> bool:
    return abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1


def act(observation: Observation) -> Action:
    grid = observation.grid
    sig = (len(grid), len(grid[0]) if grid else 0)
    if _GRID_SIG != sig:
        _build_walkable(grid)

    global _RES_TICK, _RESERVED, _RES_FROM
    if observation.tick != _RES_TICK:
        _RES_TICK = observation.tick
        _RESERVED = set()
        _RES_FROM = {}

    pos = observation.position

    # Interact when in position.
    if not observation.carrying_item and _adjacent(pos, observation.target_item_position):
        return Action.PICKUP
    drop_cell = _drop_cell_for_base(observation.base_position)
    if observation.carrying_item and pos == drop_cell:
        return Action.DROP

    goal = drop_cell if observation.carrying_item else observation.target_item_position
    dist = _dist_field(goal)

    here = dist.get(pos)
    if here is None:
        # Unreachable from here (shouldn't happen on a connected floor): hold.
        _RESERVED.add(pos)
        return Action.WAIT

    others = set(observation.all_robot_positions.values())
    others.discard(pos)

    # Rank candidate moves by resulting BFS distance to goal (lower is better).
    candidates: list[tuple[int, Action, Position]] = []
    px, py = pos
    for action, dx, dy in _DELTAS:
        nxt = (px + dx, py + dy)
        nd = dist.get(nxt)
        if nd is None:
            continue  # not walkable / off-field
        candidates.append((nd, action, nxt))
    candidates.sort(key=lambda c: c[0])

    for nd, action, nxt in candidates:
        if nxt in others:
            continue  # currently occupied by another robot
        if nxt in _RESERVED:
            continue  # another robot (higher priority) already claimed it
        # Avoid edge swaps: don't step into a cell whose occupant is reserving ours.
        if _RES_FROM.get(nxt) == pos:
            continue
        _RESERVED.add(nxt)
        _RES_FROM[nxt] = pos
        return action

    # No progress move available: stay put and reserve current cell so others
    # don't try to swap into it.
    _RESERVED.add(pos)
    _RES_FROM[pos] = pos
    return Action.WAIT
