# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 09
# job:        8cb6baa8def4  (https://refugio-hackathon-nine.vercel.app/jobs/8cb6baa8def4)
# deliveries: 398    points: 298    runtime: 29.1s
# submitted:  2026-06-27 10:19:13.935 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/8cb6baa8def4    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0398__equipo-09__8cb6baa8def4.py --count 20
# ===========================================================================

"""1213 — S1: anti-deadlock greedy (policy only).

Canonical rack-block layout (unchanged from the baseline) so any score delta is
attributable purely to the policy. The only change vs. warehouse/baseline_agent.py
is that we never WAIT into a standoff: instead of treating other robots as static
walls and stalling, we step to the unoccupied neighbour that best reduces the
precomputed distance-to-goal, sidestep when the direct cells are taken, and yield
by robot_id to match the simulator's lowest-id-wins tie-break.
"""

from __future__ import annotations

from collections import deque

from warehouse_api import Action, CellType, Observation, Position


# ---------------------------------------------------------------------------
# Layout: canonical 12 two-wide columns x 4 vertical bands == 960 shelves.
# ---------------------------------------------------------------------------
def create_layout() -> dict[str, object]:
    shelves: list[list[int]] = []
    for x0 in range(3, 48, 4):
        for y0, y1 in ((3, 12), (15, 24), (27, 36), (39, 48)):
            for x in (x0, x0 + 1):
                for y in range(y0, y1 + 1):
                    shelves.append([x, y])
    return {"schema_version": 1, "shelves": shelves}


# ---------------------------------------------------------------------------
# Static-grid precomputation, cached once per distinct grid value per process.
# ---------------------------------------------------------------------------
ACTION_DELTAS: tuple[tuple[Action, Position], ...] = (
    (Action.UP, (0, -1)),
    (Action.RIGHT, (1, 0)),
    (Action.DOWN, (0, 1)),
    (Action.LEFT, (-1, 0)),
)


class _GridIndex:
    __slots__ = ("grid", "passable", "neighbors", "dist_cache")

    def __init__(self, grid) -> None:
        self.grid = grid
        passable = frozenset(
            (x, y)
            for y, row in enumerate(grid)
            for x, cell in enumerate(row)
            if cell == CellType.EMPTY
        )
        self.passable = passable
        self.neighbors: dict[Position, tuple[tuple[Action, Position], ...]] = {
            pos: tuple(
                (action, cand)
                for action, (dx, dy) in ACTION_DELTAS
                if (cand := (pos[0] + dx, pos[1] + dy)) in passable
            )
            for pos in passable
        }
        # Distance fields keyed by frozenset of goal cells (multi-source BFS).
        self.dist_cache: dict[frozenset[Position], dict[Position, int]] = {}

    def distance_field(self, goals: frozenset[Position]) -> dict[Position, int]:
        cached = self.dist_cache.get(goals)
        if cached is not None:
            return cached
        dist: dict[Position, int] = {}
        queue: deque[Position] = deque()
        for g in goals:
            if g in self.passable:
                dist[g] = 0
                queue.append(g)
        neighbors = self.neighbors
        while queue:
            cur = queue.popleft()
            d = dist[cur] + 1
            for _action, cand in neighbors[cur]:
                if cand not in dist:
                    dist[cand] = d
                    queue.append(cand)
        self.dist_cache[goals] = dist
        return dist


_GRID_INDEX_CACHE_LIMIT = 8
_GRID_INDEXES: dict[int, _GridIndex] = {}


def _grid_index(grid) -> _GridIndex:
    key = id(grid)
    index = _GRID_INDEXES.get(key)
    if index is None:
        index = next(
            (cached for cached in _GRID_INDEXES.values() if cached.grid == grid),
            None,
        ) or _GridIndex(grid)
        _GRID_INDEXES[key] = index
        while len(_GRID_INDEXES) > _GRID_INDEX_CACHE_LIMIT:
            del _GRID_INDEXES[next(iter(_GRID_INDEXES))]
    return index


def _drop_cell_for_base(base: Position) -> Position:
    x, y = base
    if x == 0:
        return (1, y)
    if x == 51:
        return (50, y)
    if y == 0:
        return (x, 1)
    return (x, 50)


def _adjacent(a: Position, b: Position) -> bool:
    return abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1


# ---------------------------------------------------------------------------
# Policy.
# ---------------------------------------------------------------------------
def act(observation: Observation) -> Action:
    pos = observation.position

    if not observation.carrying_item and _adjacent(pos, observation.target_item_position):
        return Action.PICKUP

    drop_cell = _drop_cell_for_base(observation.base_position)
    if observation.carrying_item and pos == drop_cell:
        return Action.DROP

    index = _grid_index(observation.grid)

    if observation.carrying_item:
        goals = frozenset((drop_cell,))
    else:
        tx, ty = observation.target_item_position
        goals = frozenset(
            cand
            for cand in ((tx + 1, ty), (tx - 1, ty), (tx, ty + 1), (tx, ty - 1))
            if cand in index.passable
        )
    if not goals:
        return Action.WAIT

    dist = index.distance_field(goals)
    if dist.get(pos) is None:
        return Action.WAIT

    occupied = frozenset(
        p for rid, p in observation.all_robot_positions.items()
        if rid != observation.robot_id
    )

    # Dynamic BFS toward the goal that routes *around* currently-occupied cells.
    # Excluding occupied cells also prevents stepping into another robot, so
    # edge-swaps and head-on vertex conflicts with stationary robots can't form.
    action = _dynamic_step(pos, goals, index, dist, occupied, observation)
    if action is not None:
        return action

    # Fully boxed in by robots this tick: take the unoccupied neighbour that most
    # reduces the static distance, so we keep pushing instead of stalling.
    return _gradient_step(pos, index, dist, occupied)


def _dynamic_step(pos, goals, index, dist, occupied, observation):
    """First action of the shortest path to any goal, avoiding occupied cells.

    Expansion is ordered by static distance-to-goal so robots prefer globally
    sensible directions; ties are rotated by (robot_id, tick) to desynchronise
    robots that would otherwise pick the same contested cell.
    """
    neighbors = index.neighbors
    rot = (observation.robot_id * 2 + observation.tick) % 4

    visited = {pos}
    queue: deque[tuple[Position, Action]] = deque()
    start_nb = neighbors.get(pos, ())
    frontier = sorted(
        (
            (dist.get(cand, 1 << 30), (i + rot) % 4, action, cand)
            for i, (action, cand) in enumerate(start_nb)
            if cand not in occupied
        )
    )
    for _d, _t, action, cand in frontier:
        if cand in goals:
            return action
        visited.add(cand)
        queue.append((cand, action))

    while queue:
        cur, first = queue.popleft()
        for action, cand in neighbors[cur]:
            if cand in visited or cand in occupied:
                continue
            if cand in goals:
                return first
            visited.add(cand)
            queue.append((cand, first))
    return None


def _gradient_step(pos, index, dist, occupied):
    best_action: Action | None = None
    best_d = dist.get(pos, 1 << 30)
    for action, (dx, dy) in ACTION_DELTAS:
        cand = (pos[0] + dx, pos[1] + dy)
        if cand not in index.passable or cand in occupied:
            continue
        cand_d = dist.get(cand, 1 << 30)
        if cand_d < best_d:
            best_d = cand_d
            best_action = action
    return best_action if best_action is not None else Action.WAIT
