# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 07
# job:        4d8d233cbf6e  (https://refugio-hackathon-nine.vercel.app/jobs/4d8d233cbf6e)
# deliveries: 450    points: 0    runtime: 119.07s
# submitted:  2026-06-27 10:36:29.707 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/4d8d233cbf6e    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0450__equipo-07__4d8d233cbf6e.py --count 20
# ===========================================================================

"""Team 7 submission: canonical ring-highway layout + reserved A* routing."""

from __future__ import annotations

import heapq
from typing import NamedTuple

from warehouse_api import Action, Observation, Position

WALKABLE_MIN = 1
WALKABLE_MAX = 50
RESERVATION_HORIZON = 4
OCCUPIED_PENALTY = 50
RESERVED_PENALTY = 30
HIGHWAY_BONUS = 3

DIRECTIONS: tuple[tuple[Action, Position], ...] = (
    (Action.RIGHT, (1, 0)),
    (Action.LEFT, (-1, 0)),
    (Action.DOWN, (0, 1)),
    (Action.UP, (0, -1)),
)
DELTA_BY_ACTION: dict[Action, Position] = dict(DIRECTIONS)
NEIGHBORS: tuple[Position, ...] = ((1, 0), (-1, 0), (0, 1), (0, -1))


class _Precomputed(NamedTuple):
    walkable: frozenset[Position]
    pickup_by_shelf: dict[Position, tuple[Position, ...]]


_tick = -1
_reservations: dict[Position, int] = {}
_precomputed: _Precomputed | None = None


def create_layout() -> dict[str, object]:
    shelves: list[list[int]] = []
    for x0 in range(3, 48, 4):
        for y0, y1 in ((3, 12), (15, 24), (27, 36), (39, 48)):
            for x in (x0, x0 + 1):
                for y in range(y0, y1 + 1):
                    shelves.append([x, y])
    return {"schema_version": 1, "shelves": shelves}


def act(observation: Observation) -> Action:
    global _tick, _reservations
    _ensure_initialized()

    if observation.tick != _tick:
        _tick = observation.tick
        _reservations = {}

    if not observation.carrying_item and _adjacent(
        observation.position,
        observation.target_item_position,
    ):
        return Action.PICKUP

    drop_cell = _drop_cell_for_base(observation.base_position)
    if observation.carrying_item and observation.position == drop_cell:
        return Action.DROP

    goal = _goal_cell(observation, drop_cell)
    if goal is None:
        return Action.WAIT

    if observation.position == goal:
        return Action.WAIT

    path = _astar(observation.position, goal, observation)
    if not path:
        return _sidestep_or_wait(observation)

    _reserve_path(path, observation.tick)
    first_step = path[0]
    action = _action_to_reach(observation.position, first_step)
    if action is not None and _can_move_to(observation, first_step):
        return action
    return _sidestep_or_wait(observation)


def _ensure_initialized() -> None:
    global _precomputed
    if _precomputed is not None:
        return

    layout = create_layout()
    shelf_set = {(_cell[0], _cell[1]) for _cell in layout["shelves"]}
    walkable: set[Position] = set()
    pickup_by_shelf: dict[Position, tuple[Position, ...]] = {}

    for y in range(WALKABLE_MIN, WALKABLE_MAX + 1):
        for x in range(WALKABLE_MIN, WALKABLE_MAX + 1):
            if (x, y) not in shelf_set:
                walkable.add((x, y))

    for shelf in shelf_set:
        pickups = tuple(
            cell
            for cell in _adjacent_positions(shelf)
            if cell in walkable
        )
        pickup_by_shelf[shelf] = pickups

    _precomputed = _Precomputed(
        walkable=frozenset(walkable),
        pickup_by_shelf=pickup_by_shelf,
    )


def _goal_cell(observation: Observation, drop_cell: Position) -> Position | None:
    if observation.carrying_item:
        return drop_cell
    return _pick_best_pickup_cell(observation)


def _pick_best_pickup_cell(observation: Observation) -> Position | None:
    assert _precomputed is not None
    candidates = _precomputed.pickup_by_shelf.get(observation.target_item_position, ())
    if not candidates:
        return None

    occupied = set(observation.all_robot_positions.values())
    free = [cell for cell in candidates if cell not in occupied]
    if not free:
        return None

    start = observation.position
    return min(
        free,
        key=lambda cell: (
            _bfs_distance(start, cell),
            _congestion_near(cell, occupied),
            abs(start[0] - cell[0]) + abs(start[1] - cell[1]),
            cell[1],
            cell[0],
        ),
    )


def _astar(start: Position, goal: Position, observation: Observation) -> list[Position]:
    assert _precomputed is not None
    if start == goal:
        return []

    occupied = set(observation.all_robot_positions.values())
    carrying = observation.carrying_item
    walkable = _precomputed.walkable

    open_heap: list[tuple[int, int, Position]] = []
    counter = 0
    g_score: dict[Position, int] = {start: 0}
    came_from: dict[Position, Position] = {}
    heapq.heappush(open_heap, (_manhattan(start, goal), counter, start))

    while open_heap:
        _, _, current = heapq.heappop(open_heap)
        if current == goal:
            return _reconstruct_path(came_from, current)

        current_g = g_score[current]
        for neighbor in _neighbor_cells(current, walkable):
            if neighbor in occupied and neighbor != goal:
                continue

            move_cost = 1
            if neighbor in occupied:
                move_cost += OCCUPIED_PENALTY
            if _is_reserved(neighbor, observation.tick):
                move_cost += RESERVED_PENALTY
            if carrying and _is_highway(neighbor):
                move_cost = max(1, move_cost - HIGHWAY_BONUS)

            tentative_g = current_g + move_cost
            if tentative_g >= g_score.get(neighbor, float("inf")):
                continue

            g_score[neighbor] = tentative_g
            came_from[neighbor] = current
            counter += 1
            f_score = tentative_g + _manhattan(neighbor, goal)
            heapq.heappush(open_heap, (f_score, counter, neighbor))

    return []


def _reserve_path(path: list[Position], tick: int) -> None:
    for step_index, cell in enumerate(path[:RESERVATION_HORIZON]):
        _reservations[cell] = tick + step_index + 1


def _sidestep_or_wait(observation: Observation) -> Action:
    for action, _delta in DIRECTIONS:
        target = _step_from(observation.position, action)
        if _can_move_to(observation, target):
            return action
    return Action.WAIT


def _bfs_distance(start: Position, goal: Position) -> int:
    assert _precomputed is not None
    if start == goal:
        return 0

    walkable = _precomputed.walkable
    queue: list[Position] = [start]
    seen = {start: 0}
    head = 0
    while head < len(queue):
        current = queue[head]
        head += 1
        dist = seen[current]
        if current == goal:
            return dist
        for neighbor in _neighbor_cells(current, walkable):
            if neighbor not in seen:
                seen[neighbor] = dist + 1
                queue.append(neighbor)
    return 9999


def _congestion_near(cell: Position, occupied: set[Position]) -> int:
    cx, cy = cell
    count = 0
    for ox, oy in occupied:
        if abs(cx - ox) + abs(cy - oy) <= 2:
            count += 1
    return count


def _is_reserved(cell: Position, tick: int) -> bool:
    expiry = _reservations.get(cell)
    return expiry is not None and expiry > tick


def _is_highway(cell: Position) -> bool:
    x, y = cell
    return x in (WALKABLE_MIN, WALKABLE_MAX) or y in (WALKABLE_MIN, WALKABLE_MAX)


def _can_move_to(observation: Observation, target: Position) -> bool:
    assert _precomputed is not None
    if target not in _precomputed.walkable:
        return False
    occupied = set(observation.all_robot_positions.values())
    return target not in occupied


def _action_to_reach(start: Position, target: Position) -> Action | None:
    dx = target[0] - start[0]
    dy = target[1] - start[1]
    for action, (step_x, step_y) in DIRECTIONS:
        if (dx, dy) == (step_x, step_y):
            return action
    return None


def _reconstruct_path(came_from: dict[Position, Position], goal: Position) -> list[Position]:
    path: list[Position] = []
    current = goal
    while current in came_from:
        path.append(current)
        current = came_from[current]
    path.reverse()
    return path


def _neighbor_cells(cell: Position, walkable: frozenset[Position]) -> tuple[Position, ...]:
    x, y = cell
    return tuple(
        neighbor
        for dx, dy in NEIGHBORS
        if (neighbor := (x + dx, y + dy)) in walkable
    )


def _adjacent_positions(cell: Position) -> tuple[Position, ...]:
    x, y = cell
    return ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1))


def _adjacent(a: Position, b: Position) -> bool:
    return abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1


def _manhattan(a: Position, b: Position) -> int:
    return abs(a[0] - b[0]) + abs(a[1] - b[1])


def _step_from(position: Position, action: Action) -> Position:
    dx, dy = DELTA_BY_ACTION[action]
    x, y = position
    return (x + dx, y + dy)


def _drop_cell_for_base(base: Position) -> Position:
    x, y = base
    if y == 0:
        return (x, 1)
    if y == 51:
        return (x, 50)
    if x == 0:
        return (1, y)
    return (50, y)
