# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 13
# job:        9d741016f58e  (https://refugio-hackathon-nine.vercel.app/jobs/9d741016f58e)
# deliveries: 548    points: 0    runtime: 93.66s
# submitted:  2026-06-27 10:25:48.864 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/9d741016f58e    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0548__equipo-13__9d741016f58e.py --count 20
# ===========================================================================

from __future__ import annotations

from collections import deque

from warehouse_api import Action, CellType, Observation, Position


ACTION_DELTAS: tuple[tuple[Action, Position], ...] = (
    (Action.UP, (0, -1)),
    (Action.RIGHT, (1, 0)),
    (Action.DOWN, (0, 1)),
    (Action.LEFT, (-1, 0)),
)

DELTA_BY_ACTION = dict(ACTION_DELTAS)

_GRID_INDEXES: dict[tuple[tuple[CellType, ...], ...], dict[Position, tuple[tuple[Action, Position], ...]]] = {}
_TICK = -1
_RESERVED_DESTS: dict[Position, int] = {}
_RESERVED_EDGES: set[tuple[Position, Position]] = set()
_RESERVED_BY_ROBOT: dict[int, tuple[Position, Position]] = {}


def create_layout() -> dict[str, object]:
    shelves: list[list[int]] = []
    for x0 in range(2, 48, 3):
        for y0, y1 in ((4, 9), (12, 17), (20, 25), (28, 33), (36, 41)):
            for x in (x0, x0 + 1):
                for y in range(y0, y1 + 1):
                    shelves.append([x, y])
    return {"schema_version": 1, "shelves": shelves}


def act(observation: Observation) -> Action:
    _begin_tick(observation)

    position = observation.position
    if not observation.carrying_item and _adjacent(position, observation.target_item_position):
        _reserve(observation.robot_id, position, position)
        return Action.PICKUP

    drop_position = _drop_position_for_base(observation.base_position)
    if observation.carrying_item and position == drop_position:
        _reserve(observation.robot_id, position, position)
        return Action.DROP

    neighbors = _neighbors_for_grid(observation.grid)
    occupied = observation.all_robot_positions

    if not observation.carrying_item:
        action = _depart_base(observation, drop_position, neighbors, occupied)
        if action is not None:
            return action
        goals = _pickup_positions(observation, neighbors)
    else:
        goals = (drop_position,)

    action = _shortest_step(observation, goals, neighbors, occupied)
    return action


def _begin_tick(observation: Observation) -> None:
    global _TICK
    if observation.tick != _TICK:
        _TICK = observation.tick
        _RESERVED_DESTS.clear()
        _RESERVED_EDGES.clear()
        _RESERVED_BY_ROBOT.clear()


def _reserve(robot_id: int, start: Position, end: Position) -> None:
    old = _RESERVED_BY_ROBOT.get(robot_id)
    if old is not None:
        _RESERVED_DESTS.pop(old[1], None)
        _RESERVED_EDGES.discard(old)
    _RESERVED_BY_ROBOT[robot_id] = (start, end)
    _RESERVED_DESTS[end] = robot_id
    _RESERVED_EDGES.add((start, end))


def _neighbors_for_grid(
    grid: tuple[tuple[CellType, ...], ...],
) -> dict[Position, tuple[tuple[Action, Position], ...]]:
    cached = _GRID_INDEXES.get(grid)
    if cached is not None:
        return cached

    passable = {
        (x, y)
        for y, row in enumerate(grid)
        for x, cell in enumerate(row)
        if cell == CellType.EMPTY
    }
    neighbors = {
        position: tuple(
            (action, candidate)
            for action, (dx, dy) in ACTION_DELTAS
            if (candidate := (position[0] + dx, position[1] + dy)) in passable
        )
        for position in passable
    }
    _GRID_INDEXES[grid] = neighbors
    return neighbors


def _depart_base(
    observation: Observation,
    drop_position: Position,
    neighbors: dict[Position, tuple[tuple[Action, Position], ...]],
    occupied: object,
) -> Action | None:
    if observation.position != drop_position:
        return None

    bx, by = observation.base_position
    px, py = observation.position
    candidates = (
        (Action.DOWN, by < py),
        (Action.UP, by > py),
        (Action.RIGHT, bx < px),
        (Action.LEFT, bx > px),
    )
    for action, matches in candidates:
        if not matches:
            continue
        dx, dy = DELTA_BY_ACTION[action]
        target = (px + dx, py + dy)
        if target in neighbors and _move_is_clear(observation.robot_id, (px, py), target, occupied):
            _reserve(observation.robot_id, (px, py), target)
            return action
        _reserve(observation.robot_id, (px, py), (px, py))
        return Action.WAIT
    return None


def _pickup_positions(
    observation: Observation,
    neighbors: dict[Position, tuple[tuple[Action, Position], ...]],
) -> tuple[Position, ...]:
    px, py = observation.position
    tx, ty = observation.target_item_position
    candidates = [
        candidate
        for candidate in ((tx + 1, ty), (tx, ty + 1), (tx - 1, ty), (tx, ty - 1))
        if candidate in neighbors and _RESERVED_DESTS.get(candidate, observation.robot_id) == observation.robot_id
    ]
    candidates.sort(key=lambda cell: (abs(px - cell[0]) + abs(py - cell[1]), cell[1], cell[0]))
    return tuple(candidates)


def _shortest_step(
    observation: Observation,
    goals: tuple[Position, ...],
    neighbors: dict[Position, tuple[tuple[Action, Position], ...]],
    occupied: object,
) -> Action:
    start = observation.position
    robot_id = observation.robot_id
    if start in goals:
        _reserve(robot_id, start, start)
        return Action.WAIT
    if not goals:
        _reserve(robot_id, start, start)
        return Action.WAIT

    goal_set = frozenset(goals)
    visited = {start}
    queue: deque[tuple[Position, Action]] = deque()

    current = start
    current_first: Action | None = None
    while True:
        expansions: list[tuple[int, int, int, Action, Position]] = []
        for action, candidate in neighbors.get(current, ()):
            if candidate in visited:
                continue
            if current == start and not _move_is_clear(robot_id, start, candidate, occupied):
                continue
            best = min(abs(candidate[0] - gx) + abs(candidate[1] - gy) for gx, gy in goals)
            # Prefer unoccupied through-cells, but allow the search to route
            # through them after the first step so paths do not disappear.
            occupied_penalty = 1 if candidate in occupied.values() and candidate not in goal_set else 0
            reserved_penalty = 1 if candidate in _RESERVED_DESTS and candidate not in goal_set else 0
            expansions.append((best + occupied_penalty + reserved_penalty, candidate[1], candidate[0], action, candidate))
        expansions.sort()

        for _best, _y, _x, action, candidate in expansions:
            visited.add(candidate)
            first = action if current_first is None else current_first
            if candidate in goal_set:
                dx, dy = DELTA_BY_ACTION[first]
                target = (start[0] + dx, start[1] + dy)
                _reserve(robot_id, start, target)
                return first
            queue.append((candidate, first))

        if not queue:
            _reserve(robot_id, start, start)
            return Action.WAIT
        current, current_first = queue.popleft()


def _move_is_clear(robot_id: int, start: Position, target: Position, occupied: object) -> bool:
    reserved_by = _RESERVED_DESTS.get(target)
    if reserved_by is not None and reserved_by != robot_id:
        return False
    if (target, start) in _RESERVED_EDGES:
        return False

    occupant = None
    for other_id, position in occupied.items():
        if position == target:
            occupant = other_id
            break
    if occupant is None or occupant == robot_id:
        return True

    # A lower-id robot has already committed to leave this cell, so entering it
    # is safe as long as it is not an edge swap. Later robots are unknown.
    planned = _RESERVED_BY_ROBOT.get(occupant)
    return planned is not None and planned[1] != target and planned[1] != start


def _adjacent(a: Position, b: Position) -> bool:
    return abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1


def _drop_position_for_base(base_position: Position) -> Position:
    x, y = base_position
    if x == 0:
        return (1, y)
    if x == 51:
        return (50, y)
    if y == 0:
        return (x, 1)
    return (x, 50)
