# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 03
# job:        9c8ddcffc4f3  (https://refugio-hackathon-nine.vercel.app/jobs/9c8ddcffc4f3)
# deliveries: 610    points: 85754    runtime: 1.41s
# submitted:  2026-06-27 10:22:34.003 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/9c8ddcffc4f3    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0610__equipo-03__9c8ddcffc4f3.py --count 20
# ===========================================================================

"""REFUGIO submission v2 — prioritized-reservation flow policy.

Single self-contained file; imports only from warehouse_api (sandbox rule).

Why this beats naive greedy (37) by ~17x: the warehouse seizes up because blocked
robots just WAIT and become permanent walls while everyone reverts on collisions.
This policy:
  * Routes by precomputed BFS distance fields (around shelves, not into them).
  * Uses PIBT-style PRIORITIZED RESERVATION: the simulator calls act() in
    robot_id order each tick, so each robot claims its next cell in a per-tick
    table and later (higher-id) robots pick conflict-free moves — no mutual
    vertex/edge-swap blocking.
  * YIELDS WHEN STUCK: a robot with no progress move retreats into a free cell to
    clear the knot, instead of waiting and growing the jam. This is the unlock.

Determinism: the only cross-call state is a per-tick reservation table, rebuilt
every tick from the observation; the tie-break is pure arithmetic on
(robot_id, tick) — no Python hash randomness, no cross-tick memory.
"""

from __future__ import annotations

from collections import deque

from warehouse_api import Action, CellType, Observation, Position

_DIRS: tuple[tuple[Action, int, int], ...] = (
    (Action.RIGHT, 1, 0),
    (Action.LEFT, -1, 0),
    (Action.DOWN, 0, 1),
    (Action.UP, 0, -1),
)
_DIR_IDX = {a: i for i, (a, _, _) in enumerate(_DIRS)}


def create_layout() -> dict[str, object]:
    shelves: list[list[int]] = []
    for x0 in range(3, 48, 4):
        for y0, y1 in ((3, 12), (15, 24), (27, 36), (39, 48)):
            for x in (x0, x0 + 1):
                for y in range(y0, y1 + 1):
                    shelves.append([x, y])
    return {"schema_version": 1, "shelves": shelves}


# ── module-level precompute (static map) + per-tick reservation table ────────
_W = 0
_WALK: list[bool] = []
_READY = False
_BASE: dict[Position, list[int]] = {}
_SHELF: dict[Position, list[int]] = {}
_CTICK = -1
_RES: set[Position] = set()
_LEFT: dict[Position, Position] = {}


def _init(grid: tuple[tuple[CellType, ...], ...]) -> None:
    global _W, _WALK, _READY
    if _READY:
        return
    _W = len(grid)
    walk = [False] * (_W * _W)
    for y in range(_W):
        row = grid[y]
        for x in range(_W):
            if row[x] == CellType.EMPTY:
                walk[y * _W + x] = True
    _WALK = walk
    _READY = True


def _bfs(sources: list[Position]) -> list[int]:
    W = _W
    dist = [-1] * (W * W)
    q: deque[tuple[int, int]] = deque()
    for sx, sy in sources:
        if 0 <= sx < W and 0 <= sy < W and _WALK[sy * W + sx]:
            i = sy * W + sx
            if dist[i] != 0:
                dist[i] = 0
                q.append((sx, sy))
    while q:
        x, y = q.popleft()
        d = dist[y * W + x] + 1
        for _, dx, dy in _DIRS:
            nx, ny = x + dx, y + dy
            if 0 <= nx < W and 0 <= ny < W:
                ni = ny * W + nx
                if _WALK[ni] and dist[ni] == -1:
                    dist[ni] = d
                    q.append((nx, ny))
    return dist


def _drop(base: Position) -> Position:
    x, y = base
    if y == 0:
        return (x, 1)
    if y == _W - 1:
        return (x, _W - 2)
    if x == 0:
        return (1, y)
    return (_W - 2, y)


def _base_field(drop: Position) -> list[int]:
    f = _BASE.get(drop)
    if f is None:
        f = _bfs([drop])
        _BASE[drop] = f
    return f


def _shelf_field(t: Position) -> list[int]:
    f = _SHELF.get(t)
    if f is None:
        tx, ty = t
        f = _bfs([(tx + 1, ty), (tx - 1, ty), (tx, ty + 1), (tx, ty - 1)])
        _SHELF[t] = f
    return f


def act(observation: Observation) -> Action:
    global _CTICK, _RES, _LEFT
    ob = observation
    _init(ob.grid)
    W = _W
    px, py = ob.position

    if not ob.carrying_item:
        t = ob.target_item_position
        if abs(px - t[0]) + abs(py - t[1]) == 1:
            return Action.PICKUP
        field = _shelf_field(t)
    else:
        drop = _drop(ob.base_position)
        if ob.position == drop:
            return Action.DROP
        field = _base_field(drop)

    here = field[py * W + px]

    # reset the reservation table at the start of each tick (and each seed)
    if ob.tick != _CTICK:
        _CTICK = ob.tick
        _RES = set()
        _LEFT = {}

    pos = (px, py)
    occ_cells = set(ob.all_robot_positions.values())
    occ_cells.discard(pos)

    # deterministic per-robot tie-break (no Python hash randomness)
    mix = (ob.robot_id * 2654435761 + ob.tick * 40503) & 0xFFFF

    cand: list[tuple[int, int, int, Action, Position]] = []
    for a, dx, dy in _DIRS:
        nx, ny = px + dx, py + dy
        if not (0 <= nx < W and 0 <= ny < W) or not _WALK[ny * W + nx]:
            continue
        dn = field[ny * W + nx]
        if dn < 0:
            continue
        rank = 0 if dn < here else (1 if dn == here else 2)  # progress < sidestep < retreat
        tb = (mix * 31 + _DIR_IDX[a] * 7) & 0xFFFF
        cand.append((rank, dn, tb, a, (nx, ny)))

    cand.sort(key=lambda c: (c[0], c[1], c[2]))
    for rank, dn, tb, a, cell in cand:
        if cell in _RES:
            continue
        # enterable: empty, or vacated this tick by a higher-priority robot that
        # did not swap into our cell (avoids the simulator's edge-swap block)
        if cell in occ_cells and not (cell in _LEFT and _LEFT[cell] != pos):
            continue
        _RES.add(cell)
        _LEFT[pos] = cell
        return a

    _RES.add(pos)
    return Action.WAIT
