# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 06
# job:        4fbc4e182b67  (https://refugio-hackathon-nine.vercel.app/jobs/4fbc4e182b67)
# deliveries: 730    points: 0    runtime: 3.19s
# submitted:  2026-06-27 10:29:39.819 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/4fbc4e182b67    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0730__equipo-06__4fbc4e182b67.py --count 20
# ===========================================================================

"""REFUGIO submission v3 — Hybrid Dijkstra Lane Navigation with Prioritized-Reservation & Yielding."""

from __future__ import annotations

import heapq
from collections import deque

from warehouse_api import Action, CellType, Observation, Position

_DIRS: tuple[tuple[Action, int, int], ...] = (
    (Action.RIGHT, 1, 0),
    (Action.LEFT, -1, 0),
    (Action.DOWN, 0, 1),
    (Action.UP, 0, -1),
)
_DIR_IDX = {a: i for i, (a, _, _) in enumerate(_DIRS)}

_OPPOSITE_ACTION = {
    Action.RIGHT: Action.LEFT,
    Action.LEFT: Action.RIGHT,
    Action.DOWN: Action.UP,
    Action.UP: Action.DOWN,
}


def create_layout() -> dict[str, object]:
    """Return the canonical high-density warehouse layout."""
    shelves: list[list[int]] = []
    for x0 in range(3, 48, 4):
        for y0, y1 in ((3, 12), (15, 24), (27, 36), (39, 48)):
            for x in (x0, x0 + 1):
                for y in range(y0, y1 + 1):
                    shelves.append([x, y])
    return {"schema_version": 1, "shelves": shelves}


# ── global precomputes and per-tick reservation tables ────────
_W = 0
_WALK: list[bool] = []
_READY = False
_BASE: dict[Position, list[float]] = {}
_SHELF: dict[Position, list[float]] = {}
_CTICK = -1
_RES: set[Position] = set()
_LEFT: dict[Position, Position] = {}


def _init(grid: tuple[tuple[CellType, ...], ...]) -> None:
    global _W, _WALK, _READY
    if _READY:
        return
    _W = len(grid)
    walk = [False] * (_W * _W)
    for y in range(_W):
        row = grid[y]
        for x in range(_W):
            if row[x] == CellType.EMPTY:
                walk[y * _W + x] = True
    _WALK = walk
    _READY = True


def preferred_direction_action(x: int, y: int) -> Action | None:
    """Define traffic lane directions for maximum throughput and 0 collisions."""
    # Perimeter (Autopista) Roundabout
    if 1 <= x <= 2:
        return Action.UP
    if 49 <= x <= 50:
        return Action.DOWN
    if 1 <= y <= 2:
        return Action.RIGHT
    if 49 <= y <= 50:
        return Action.LEFT

    # Internal vertical aisles (two-lane system)
    if x in (5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45):
        return Action.UP
    if x in (6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46):
        return Action.DOWN

    # Internal horizontal aisles (two-lane system)
    if y in (13, 25, 37):
        return Action.RIGHT
    if y in (14, 26, 38):
        return Action.LEFT

    return None


def get_move_cost(x: int, y: int, action: Action) -> float:
    """Return transition cost. Heavily penalize going against preferred traffic."""
    pref = preferred_direction_action(x, y)
    if pref is None:
        return 1.0
    if action == pref:
        return 1.0
    if action == _OPPOSITE_ACTION.get(pref):
        return 15.0
    return 3.0


def _dijkstra(sources: list[Position]) -> list[float]:
    """Compute shortest path costs from all cells to target sources backwards."""
    W = _W
    dist = [1e9] * (W * W)
    pq: list[tuple[float, int]] = []

    for sx, sy in sources:
        if 0 <= sx < W and 0 <= sy < W and _WALK[sy * W + sx]:
            i = sy * W + sx
            dist[i] = 0.0
            heapq.heappush(pq, (0.0, i))

    while pq:
        d, i = heapq.heappop(pq)

        if d > dist[i]:
            continue

        cy = i // W
        cx = i % W

        for a, dx, dy in _DIRS:
            nx, ny = cx + dx, cy + dy
            if 0 <= nx < W and 0 <= ny < W:
                ni = ny * W + nx
                if _WALK[ni]:
                    # The action taken at (nx, ny) to move to (cx, cy) is op_a
                    op_a = _OPPOSITE_ACTION[a]
                    cost = d + get_move_cost(nx, ny, op_a)
                    if cost < dist[ni]:
                        dist[ni] = cost
                        heapq.heappush(pq, (cost, ni))

    return dist


def _drop(base: Position) -> Position:
    """Return the walkable interior cell adjacent to an external base."""
    x, y = base
    if y == 0:
        return (x, 1)
    if y == _W - 1:
        return (x, _W - 2)
    if x == 0:
        return (1, y)
    return (_W - 2, y)


def _base_field(drop: Position) -> list[float]:
    """Get or compute the Dijkstra cost field to a base drop-off."""
    f = _BASE.get(drop)
    if f is None:
        f = _dijkstra([drop])
        _BASE[drop] = f
    return f


def _shelf_field(t: Position) -> list[float]:
    """Get or compute the Dijkstra cost field to a shelf pickup."""
    f = _SHELF.get(t)
    if f is None:
        tx, ty = t
        f = _dijkstra([(tx + 1, ty), (tx - 1, ty), (tx, ty + 1), (tx, ty - 1)])
        _SHELF[t] = f
    return f


def act(observation: Observation) -> Action:
    """Determine the optimal collision-free action with traffic lanes, prioritized reservations, and yielding."""
    global _CTICK, _RES, _LEFT
    ob = observation
    _init(ob.grid)
    W = _W
    px, py = ob.position

    # 1. Handle pickup or drop actions first
    if not ob.carrying_item:
        t = ob.target_item_position
        if abs(px - t[0]) + abs(py - t[1]) == 1:
            return Action.PICKUP
        field = _shelf_field(t)
    else:
        drop = _drop(ob.base_position)
        if ob.position == drop:
            return Action.DROP
        field = _base_field(drop)

    here = field[py * W + px]

    # Reset the reservation tables at the start of each tick
    if ob.tick != _CTICK:
        _CTICK = ob.tick
        _RES = set()
        _LEFT = {}

    pos = (px, py)
    occ_cells = set(ob.all_robot_positions.values())
    occ_cells.discard(pos)

    # Deterministic per-robot tie-break (no Python hash randomness)
    mix = (ob.robot_id * 2654435761 + ob.tick * 40503) & 0xFFFF

    # Evaluate move candidates
    cand: list[tuple[int, float, int, Action, Position]] = []
    for a, dx, dy in _DIRS:
        nx, ny = px + dx, py + dy
        if not (0 <= nx < W and 0 <= ny < W) or not _WALK[ny * W + nx]:
            continue
        dn = field[ny * W + nx]
        if dn >= 1e9:
            continue

        # Classify moves: progress < sidestep < retreat
        # Using a tiny epsilon to handle floating point comparisons safely
        if dn < here - 1e-5:
            rank = 0
        elif abs(dn - here) < 1e-5:
            rank = 1
        else:
            rank = 2

        tb = (mix * 31 + _DIR_IDX[a] * 7) & 0xFFFF
        cand.append((rank, dn, tb, a, (nx, ny)))

    # Sort: prioritizing progress rank first, then raw Dijkstra cost, then tie-breaker
    cand.sort(key=lambda c: (c[0], c[1], c[2]))

    # Attempt to reserve the best available move candidate
    for rank, dn, tb, a, cell in cand:
        if cell in _RES:
            continue
        # Enterable if unoccupied, or vacated this tick by a higher-priority robot
        # that did not swap into our cell (avoids edge-swapping block)
        if cell in occ_cells and not (cell in _LEFT and _LEFT[cell] != pos):
            continue
        _RES.add(cell)
        _LEFT[pos] = cell
        return a

    # Wait if completely blocked
    _RES.add(pos)
    return Action.WAIT
