# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 04
# job:        593ee5cec900  (https://refugio-hackathon-nine.vercel.app/jobs/593ee5cec900)
# deliveries: 749    points: 0    runtime: 4.03s
# submitted:  2026-06-27 11:51:23.094 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/593ee5cec900    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0749__equipo-04__593ee5cec900.py --count 20
# ===========================================================================

"""REFUGIO Warehouse Challenge — Balanced Performance Policy.

create_layout() : canonical 2-wide-aisle racks (exactly 960 shelves, valid).
act(observation): ONE-WAY ("highway") routing + decentralized merge arbitration.
"""

from warehouse_api import Action, Observation  # noqa: F401
from collections import deque


# --------------------------------------------------------------------------- #
# Layout
# --------------------------------------------------------------------------- #
def _build_shelves():
    shelves = []
    for x0 in range(3, 48, 4):                       # 3,7,...,47 (12 column pairs)
        for y0, y1 in ((3, 12), (15, 24), (27, 36), (39, 48)):
            for x in (x0, x0 + 1):
                for y in range(y0, y1 + 1):
                    shelves.append((x, y))
    return shelves


def create_layout():
    return {"schema_version": 1, "shelves": [[x, y] for (x, y) in _build_shelves()]}


# --------------------------------------------------------------------------- #
# Static Graph Logic
# --------------------------------------------------------------------------- #
_FLOOR = None              # frozenset of walkable interior cells
_field_dir = {}            # goal-key -> directed distance field

_DIRS = (((1, 0), Action.RIGHT), ((-1, 0), Action.LEFT),
         ((0, 1), Action.DOWN), ((0, -1), Action.UP))   # +y = down, -y = up


def _ensure_init():
    global _FLOOR
    if _FLOOR is not None:
        return
    shelves = set(_build_shelves())
    _FLOOR = frozenset(
        (x, y)
        for x in range(1, 51)
        for y in range(1, 51)
        if (x, y) not in shelves
    )


def _fwd_outs(pos):
    x, y = pos
    outs = []
    nb = (x, y - 1) if x & 1 else (x, y + 1)         # vertical lane
    if nb in _FLOOR:
        outs.append((Action.UP if x & 1 else Action.DOWN, nb))
    nb = (x - 1, y) if y & 1 else (x + 1, y)         # horizontal lane
    if nb in _FLOOR:
        outs.append((Action.LEFT if y & 1 else Action.RIGHT, nb))
    return outs


def _preds(cell):
    x, y = cell
    return (
        (x, y + 1) if x & 1 else (x, y - 1),
        (x + 1, y) if y % 2 != 0 else (x - 1, y),
    )


def _bfs_dir(goals):
    dist = {}
    dq = deque()
    for g in goals:
        if g in _FLOOR and g not in dist:
            dist[g] = 0
            dq.append(g)
    while dq:
        v = dq.popleft()
        nd = dist[v] + 1
        for w in _preds(v):
            if w in _FLOOR and w not in dist:
                dist[w] = nd
                dq.append(w)
    return dist


def _field_dir_shelf(shelf):
    k = ("s", shelf)
    f = _field_dir.get(k)
    if f is None:
        sx, sy = shelf
        goals = [(sx + dx, sy + dy) for (dx, dy), _a in _DIRS]
        f = _bfs_dir(goals)
        _field_dir[k] = f
    return f


def _field_dir_cell(cell):
    k = ("c", cell)
    f = _field_dir.get(k)
    if f is None:
        f = _bfs_dir([cell])
        _field_dir[k] = f
    return f


# --------------------------------------------------------------------------- #
# Decision Logic
# --------------------------------------------------------------------------- #
def _xy(p):
    try:
        return int(p[0]), int(p[1])
    except (TypeError, KeyError, IndexError, AttributeError):
        return int(p.x), int(p.y)


def _entry_of_base(base):
    bx, by = _xy(base)
    return (min(max(bx, 1), 50), min(max(by, 1), 50))


def _priority_key(rid, tick):
    return ((rid * 2654435761 + tick * 40503) & 0xFFFF, rid)


def _can_enter(cell, all_positions, rid, tick):
    p1, p2 = _preds(cell)
    mine = _priority_key(rid, tick)
    items = all_positions.items() if hasattr(all_positions, "items") else enumerate(all_positions)
    for other_id, pos in items:
        if other_id == rid: continue
        p = _xy(pos)
        if (p == p1 or p == p2) and _priority_key(other_id, tick) < mine:
            return False
    return True


def act(observation):
    try:
        _ensure_init()
        x, y = _xy(observation.position)
        pos = (x, y)
        carrying = bool(observation.carrying_item)

        if not carrying:
            sx, sy = _xy(observation.target_item_position)
            if abs(sx - x) + abs(sy - y) == 1:
                return Action.PICKUP
            field = _field_dir_shelf((sx, sy))
        else:
            entry = _entry_of_base(observation.base_position)
            if pos == entry:
                return Action.DROP
            field = _field_dir_cell(entry)

        arp = observation.all_robot_positions
        rid = observation.robot_id
        tick = observation.tick
        occ = set()
        items = arp.items() if hasattr(arp, "items") else enumerate(arp)
        for k, v in items:
            if k != rid: occ.add(_xy(v))

        d_here = field.get(pos)
        if d_here is None: return Action.WAIT

        outs = []
        for a, nb in _fwd_outs(pos):
            dn = field.get(nb)
            if dn is not None and dn < d_here:
                outs.append((dn, a, nb))
        outs.sort(key=lambda t: t[0])

        for dn, a, nb in outs:
            if nb not in occ and _can_enter(nb, arp, rid, tick):
                return a
        for dn, a, nb in outs:
            if nb in occ: return a
        return Action.WAIT
    except Exception:
        return Action.WAIT
