# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 10
# job:        8960d3b7806b  (https://refugio-hackathon-nine.vercel.app/jobs/8960d3b7806b)
# deliveries: 759    points: 0    runtime: 1.42s
# submitted:  2026-06-27 10:50:43.310 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/8960d3b7806b    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0759__equipo-10__8960d3b7806b.py --count 20
# ===========================================================================

"""RAMA B candidate — PIBT-style coordinated policy.

Our BFS floor (~131/seed, 397 oficial) routes each robot around shelves but
treats other robots as walls and WAITs when boxed in — robots collide (the sim
reverts one) and stall. This adds cooperative collision handling:

  1. Distance-to-goal FIELDS, one BFS per target/base from the goal to every
     cell, cached at module level -> act() is O(1) per call (no BFS per tick).
  2. Per-tick RESERVATION: each robot claims its next cell; two robots never
     take the same cell, so no collision-reverts.
  3. FOLLOW-MOVES: you may enter an occupied cell if its occupant is itself
     vacating -> trains of robots flow down aisles instead of jamming.
  4. Rotational tie-break (robot_id+tick)%4 + YIELD: desynchronise robots and
     step aside to any free cell instead of WAITing.

PIBT = Priority Inheritance with Backtracking (Okumura et al.), the standard
real-time MAPF method. This is our own implementation of that idea — the team's
earlier *naive* reservation regressed ~5x precisely because it lacked the
follow-moves + desync + yield below.

  python tools/check_submission.py submissions/policy_pibt.py
  python tools/benchmark.py submissions/policy_pibt.py --count 20
"""

from __future__ import annotations

from collections import deque

from warehouse_api import Action, CellType, Observation, Position

# Direction order; rotated per (robot, tick) to break symmetry.
_DIRS: tuple[tuple[Action, int, int], ...] = (
    (Action.RIGHT, 1, 0),
    (Action.LEFT, -1, 0),
    (Action.DOWN, 0, 1),
    (Action.UP, 0, -1),
)
_DELTAS: tuple[tuple[int, int], ...] = ((1, 0), (-1, 0), (0, 1), (0, -1))

# Static structures, built once from the (constant) grid.
_W = 0
_WALK: tuple[bool, ...] = ()
_READY = False
# Cached distance fields: goal region -> distance to every cell.
_SHELF_FIELD: dict[Position, list[int]] = {}
_BASE_FIELD: dict[Position, list[int]] = {}
_DROP: dict[Position, Position] = {}
# Per-tick reservation state, reset when the tick advances.
_TICK = -1
_RESERVED: set[Position] = set()
_LEAVING: dict[Position, Position] = {}  # cell -> where its occupant is moving


def create_layout() -> dict[str, object]:
    # ponytail: baseline grid; RAMA A owns layout. PIBT scores on layout quality.
    shelves: list[list[int]] = []
    for x0 in range(3, 48, 4):
        for y0, y1 in ((3, 12), (15, 24), (27, 36), (39, 48)):
            for x in (x0, x0 + 1):
                for y in range(y0, y1 + 1):
                    shelves.append([x, y])
    return {"schema_version": 1, "shelves": shelves}


def _build(grid: tuple[tuple[CellType, ...], ...]) -> None:
    global _W, _WALK, _READY
    if _READY:
        return
    _W = len(grid)
    _WALK = tuple(
        grid[y][x] == CellType.EMPTY for y in range(_W) for x in range(_W)
    )
    _READY = True


def _bfs_field(sources: list[Position]) -> list[int]:
    """Step distance from any source cell to every walkable cell (-1 if none)."""
    w = _W
    dist = [-1] * (w * w)
    queue: deque[tuple[int, int]] = deque()
    for sx, sy in sources:
        if 0 <= sx < w and 0 <= sy < w and _WALK[sy * w + sx]:
            idx = sy * w + sx
            if dist[idx] == -1:
                dist[idx] = 0
                queue.append((sx, sy))
    while queue:
        x, y = queue.popleft()
        nd = dist[y * w + x] + 1
        for dx, dy in _DELTAS:
            nx, ny = x + dx, y + dy
            if 0 <= nx < w and 0 <= ny < w:
                ni = ny * w + nx
                if _WALK[ni] and dist[ni] == -1:
                    dist[ni] = nd
                    queue.append((nx, ny))
    return dist


def _drop_cell(base: Position) -> Position:
    cached = _DROP.get(base)
    if cached is None:
        x, y = base
        if y == 0:
            cached = (x, 1)
        elif y == _W - 1:
            cached = (x, _W - 2)
        elif x == 0:
            cached = (1, y)
        else:
            cached = (_W - 2, y)
        _DROP[base] = cached
    return cached


def _base_field(drop: Position) -> list[int]:
    field = _BASE_FIELD.get(drop)
    if field is None:
        field = _bfs_field([drop])
        _BASE_FIELD[drop] = field
    return field


def _shelf_field(target: Position) -> list[int]:
    field = _SHELF_FIELD.get(target)
    if field is None:
        tx, ty = target
        sources = [(tx + dx, ty + dy) for dx, dy in _DELTAS]
        field = _bfs_field(sources)
        _SHELF_FIELD[target] = field
    return field


def act(observation: Observation) -> Action:
    global _TICK, _RESERVED, _LEAVING
    ob = observation
    _build(ob.grid)
    w = _W
    px, py = ob.position

    if not ob.carrying_item:
        tx, ty = ob.target_item_position
        if abs(px - tx) + abs(py - ty) == 1:
            return Action.PICKUP
        field = _shelf_field(ob.target_item_position)
    else:
        drop = _drop_cell(ob.base_position)
        if (px, py) == drop:
            return Action.DROP
        field = _base_field(drop)

    if ob.tick != _TICK:
        _TICK = ob.tick
        _RESERVED = set()
        _LEAVING = {}

    pos = (px, py)
    here = field[py * w + px]
    occupied = set(ob.all_robot_positions.values())
    occupied.discard(pos)
    rot = (ob.robot_id + ob.tick) % 4

    def claim(cell: Position, action: Action) -> Action:
        _RESERVED.add(cell)
        _LEAVING[pos] = cell
        return action

    def free(cell: Position) -> bool:
        if cell in _RESERVED:
            return False
        # Enter an occupied cell only if its occupant is vacating (not swapping).
        if cell in occupied and _LEAVING.get(cell, pos) == pos:
            return False
        return True

    # Ranked candidates: toward goal (0), sideways (1), away (2). Reachable only.
    ranked: list[tuple[int, int, int, Action, Position]] = []
    for i in range(4):
        action, dx, dy = _DIRS[(i + rot) % 4]
        nx, ny = px + dx, py + dy
        if not (0 <= nx < w and 0 <= ny < w and _WALK[ny * w + nx]):
            continue
        dn = field[ny * w + nx]
        if dn < 0:
            continue
        rank = 0 if dn < here else (1 if dn == here else 2)
        ranked.append((rank, dn, i, action, (nx, ny)))
    ranked.sort()
    for _rank, _dn, _i, action, cell in ranked:
        if free(cell):
            return claim(cell, action)

    # Last-resort yield: any free neighbour, even a dead pocket, to unstick.
    for i in range(4):
        action, dx, dy = _DIRS[(i + rot) % 4]
        nx, ny = px + dx, py + dy
        if 0 <= nx < w and 0 <= ny < w and _WALK[ny * w + nx] and free((nx, ny)):
            return claim((nx, ny), action)

    _RESERVED.add(pos)
    return Action.WAIT
