# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 08
# job:        e8ad7754c58a  (https://refugio-hackathon-nine.vercel.app/jobs/e8ad7754c58a)
# deliveries: 759    points: 87165    runtime: 1.4s
# submitted:  2026-06-27 10:29:25.769 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/e8ad7754c58a    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0759__equipo-08__e8ad7754c58a.py --count 20
# ===========================================================================

"""REFUGIO submission v3 — PIBT with rotational tie-breaking.

Key improvements:
1. Rotational tie-breaking per (robot_id, tick) to desynchronize robots
2. Better yield: prefer cells closer to goal when retreating
3. Pre-computed walkable set for faster neighbor checks
4. Optimized BFS with early termination for single goals
"""

from __future__ import annotations

from collections import deque

from warehouse_api import Action, CellType, Observation, Position

_DIRS: tuple[tuple[Action, int, int], ...] = (
    (Action.RIGHT, 1, 0),
    (Action.LEFT, -1, 0),
    (Action.DOWN, 0, 1),
    (Action.UP, 0, -1),
)
_DIR_DELTAS = [(1, 0), (-1, 0), (0, 1), (0, -1)]


def create_layout() -> dict[str, object]:
    shelves: list[list[int]] = []
    for x0 in range(3, 48, 4):
        for y0, y1 in ((3, 12), (15, 24), (27, 36), (39, 48)):
            for x in (x0, x0 + 1):
                for y in range(y0, y1 + 1):
                    shelves.append([x, y])
    return {"schema_version": 1, "shelves": shelves}


# ── module-level precompute ──────────────────────────────────────────────────
_W = 0
_WALK: list[bool] = []
_READY = False
_BASE: dict[Position, list[int]] = {}
_SHELF: dict[Position, list[int]] = {}
_DROP_POS: dict[Position, Position] = {}
_CTICK = -1
_RES: set[Position] = set()
_LEFT: dict[Position, Position] = {}


def _init(grid: tuple[tuple[CellType, ...], ...]) -> None:
    global _W, _WALK, _READY
    if _READY:
        return
    _W = len(grid)
    walk = [False] * (_W * _W)
    for y in range(_W):
        row = grid[y]
        for x in range(_W):
            if row[x] == CellType.EMPTY:
                walk[y * _W + x] = True
    _WALK = walk
    _READY = True


def _bfs(sources: list[Position]) -> list[int]:
    W = _W
    dist = [-1] * (W * W)
    q: deque[tuple[int, int]] = deque()
    for sx, sy in sources:
        if 0 <= sx < W and 0 <= sy < W and _WALK[sy * W + sx]:
            i = sy * W + sx
            if dist[i] != 0:
                dist[i] = 0
                q.append((sx, sy))
    while q:
        x, y = q.popleft()
        d = dist[y * W + x] + 1
        for dx, dy in _DIR_DELTAS:
            nx, ny = x + dx, y + dy
            if 0 <= nx < W and 0 <= ny < W:
                ni = ny * W + nx
                if _WALK[ni] and dist[ni] == -1:
                    dist[ni] = d
                    q.append((nx, ny))
    return dist


def _drop(base: Position) -> Position:
    cached = _DROP_POS.get(base)
    if cached is not None:
        return cached
    x, y = base
    if y == 0:
        result = (x, 1)
    elif y == _W - 1:
        result = (x, _W - 2)
    elif x == 0:
        result = (1, y)
    else:
        result = (_W - 2, y)
    _DROP_POS[base] = result
    return result


def _base_field(drop: Position) -> list[int]:
    f = _BASE.get(drop)
    if f is None:
        f = _bfs([drop])
        _BASE[drop] = f
    return f


def _shelf_field(t: Position) -> list[int]:
    f = _SHELF.get(t)
    if f is None:
        tx, ty = t
        sources = []
        for dx, dy in _DIR_DELTAS:
            nx, ny = tx + dx, ty + dy
            if 0 <= nx < _W and 0 <= ny < _W and _WALK[ny * _W + nx]:
                sources.append((nx, ny))
        f = _bfs(sources)
        _SHELF[t] = f
    return f


def _is_valid(nx: int, ny: int) -> bool:
    return 0 <= nx < _W and 0 <= ny < _W and _WALK[ny * _W + nx]


def act(observation: Observation) -> Action:
    global _CTICK, _RES, _LEFT
    ob = observation
    _init(ob.grid)
    W = _W
    px, py = ob.position

    if not ob.carrying_item:
        t = ob.target_item_position
        if abs(px - t[0]) + abs(py - t[1]) == 1:
            return Action.PICKUP
        field = _shelf_field(t)
    else:
        drop = _drop(ob.base_position)
        if ob.position == drop:
            return Action.DROP
        field = _base_field(drop)

    here = field[py * W + px]

    if ob.tick != _CTICK:
        _CTICK = ob.tick
        _RES = set()
        _LEFT = {}

    pos = (px, py)
    occ_cells = set(ob.all_robot_positions.values())
    occ_cells.discard(pos)

    # Rotational tie-breaking: rotate direction priority per robot_id and tick
    # This desynchronizes robots that would otherwise pick the same cell
    rot = (ob.robot_id + ob.tick) % 4

    # Build candidates with rotated direction order
    cand: list[tuple[int, int, int, Action, Position]] = []
    for i in range(4):
        di = (i + rot) % 4
        a, dx, dy = _DIRS[di]
        nx, ny = px + dx, py + dy
        if not _is_valid(nx, ny):
            continue
        dn = field[ny * W + nx]
        if dn < 0:
            continue
        rank = 0 if dn < here else (1 if dn == here else 2)
        cand.append((rank, dn, i, a, (nx, ny)))

    cand.sort(key=lambda c: (c[0], c[1], c[2]))

    # Try to claim a cell in priority order
    for rank, dn, tb, a, cell in cand:
        if cell in _RES:
            continue
        if cell in occ_cells and not (cell in _LEFT and _LEFT[cell] != pos):
            continue
        _RES.add(cell)
        _LEFT[pos] = cell
        return a

    # YIELD: try to move to ANY free cell, preferring closer to goal
    yield_cand: list[tuple[int, Action, Position]] = []
    for i in range(4):
        di = (i + rot) % 4
        a, dx, dy = _DIRS[di]
        nx, ny = px + dx, py + dy
        if not _is_valid(nx, ny):
            continue
        cell = (nx, ny)
        if cell in _RES:
            continue
        if cell in occ_cells and not (cell in _LEFT and _LEFT[cell] != pos):
            continue
        dn = field[ny * W + nx]
        yield_cand.append((dn, a, cell))

    if yield_cand:
        yield_cand.sort(key=lambda c: c[0])
        _, a, cell = yield_cand[0]
        _RES.add(cell)
        _LEFT[pos] = cell
        return a

    _RES.add(pos)
    return Action.WAIT
