# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 05
# job:        754cabbf101e  (https://refugio-hackathon-nine.vercel.app/jobs/754cabbf101e)
# deliveries: 783    points: 0    runtime: 3.02s
# submitted:  2026-06-27 10:33:30.429 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/754cabbf101e    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0783__equipo-05__754cabbf101e.py --count 20
# ===========================================================================

"""REFUGIO Team 5 - reservation-table submission.

Competitive version: uses the deterministic per-tick call order to reserve
intended destinations, preventing most vertex conflicts and edge swaps.
"""

from __future__ import annotations

from collections import deque

from warehouse_api import Action, Observation


SIZE = 52
INF = 10_000

DIRS = (
    (Action.RIGHT, 1, 0),
    (Action.LEFT, -1, 0),
    (Action.DOWN, 0, 1),
    (Action.UP, 0, -1),
)


def _build_shelves() -> tuple[tuple[int, int], ...]:
    shelves: list[tuple[int, int]] = []
    for x0 in range(3, 48, 4):
        for y0, y1 in ((3, 12), (15, 24), (27, 36), (39, 48)):
            for x in (x0, x0 + 1):
                for y in range(y0, y1 + 1):
                    shelves.append((x, y))
    return tuple(shelves)


SHELVES = _build_shelves()
SHELF_SET = frozenset(SHELVES)
EMPTY_SET = frozenset(
    (x, y)
    for y in range(1, 51)
    for x in range(1, 51)
    if (x, y) not in SHELF_SET
)
SHELVES_JSON = [[x, y] for x, y in SHELVES]


def _idx(cell: tuple[int, int]) -> int:
    return cell[1] * SIZE + cell[0]


def _drop_cell_for_base(base: tuple[int, int]) -> tuple[int, int]:
    x, y = base
    if y == 0:
        return (x, 1)
    if y == 51:
        return (x, 50)
    if x == 0:
        return (1, y)
    return (50, y)


def _pickup_cells_for_shelf(shelf: tuple[int, int]) -> tuple[tuple[int, int], ...]:
    x, y = shelf
    cells = []
    for cell in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
        if cell in EMPTY_SET:
            cells.append(cell)
    return tuple(cells)


PICKUP_CELLS = {shelf: _pickup_cells_for_shelf(shelf) for shelf in SHELVES}


def _bfs_from(goal: tuple[int, int]) -> tuple[int, ...]:
    dist = [INF] * (SIZE * SIZE)
    dist[_idx(goal)] = 0
    q: deque[tuple[int, int]] = deque([goal])
    while q:
        x, y = q.popleft()
        nd = dist[_idx((x, y))] + 1
        for _action, dx, dy in DIRS:
            nxt = (x + dx, y + dy)
            if nxt in EMPTY_SET:
                ni = _idx(nxt)
                if dist[ni] == INF:
                    dist[ni] = nd
                    q.append(nxt)
    return tuple(dist)


DIST = {cell: _bfs_from(cell) for cell in EMPTY_SET}

_tick = -1
_reserved: set[tuple[int, int]] = set()
_moves: dict[int, tuple[tuple[int, int], tuple[int, int]]] = {}


def create_layout() -> dict[str, object]:
    return {"schema_version": 1, "shelves": SHELVES_JSON}


def act(observation: Observation) -> Action:
    _begin_tick(observation.tick)

    pos = observation.position
    if not observation.carrying_item and _adjacent(pos, observation.target_item_position):
        return _record(observation.robot_id, pos, Action.PICKUP)

    drop_cell = _drop_cell_for_base(observation.base_position)
    if observation.carrying_item and pos == drop_cell:
        return _record(observation.robot_id, pos, Action.DROP)

    if observation.carrying_item:
        goal = drop_cell
    else:
        goal = _best_pickup_goal(observation)
        if goal is None:
            return _record(observation.robot_id, pos, Action.WAIT)

    return _record(observation.robot_id, pos, _step_toward(observation, goal))


def _begin_tick(tick: int) -> None:
    global _tick, _reserved, _moves
    if tick != _tick:
        _tick = tick
        _reserved = set()
        _moves = {}


def _record(robot_id: int, pos: tuple[int, int], action: Action) -> Action:
    dest = _destination(pos, action)
    _reserved.add(dest)
    _moves[robot_id] = (pos, dest)
    return action


def _destination(pos: tuple[int, int], action: Action) -> tuple[int, int]:
    x, y = pos
    if action == Action.RIGHT:
        return (x + 1, y)
    if action == Action.LEFT:
        return (x - 1, y)
    if action == Action.DOWN:
        return (x, y + 1)
    if action == Action.UP:
        return (x, y - 1)
    return pos


def _adjacent(a: tuple[int, int], b: tuple[int, int]) -> bool:
    return abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1


def _best_pickup_goal(observation: Observation) -> tuple[int, int] | None:
    pos = observation.position
    best_cell = None
    best_score = INF
    for cell in PICKUP_CELLS.get(observation.target_item_position, ()):
        score = DIST[cell][_idx(pos)]
        if score < best_score:
            best_score = score
            best_cell = cell
    return best_cell


def _step_toward(observation: Observation, goal: tuple[int, int]) -> Action:
    pos = observation.position
    current_d = DIST[goal][_idx(pos)]
    must_vacate = any(dest == pos and start != pos for start, dest in _moves.values())

    best_action = Action.WAIT
    best_score = current_d * 100 + 800

    for action, dx, dy in DIRS:
        nxt = (pos[0] + dx, pos[1] + dy)
        if nxt not in EMPTY_SET:
            continue

        d = DIST[goal][_idx(nxt)]
        if d >= INF:
            continue

        score = d * 100
        if nxt in _reserved:
            score += 1_000
        if _would_edge_swap(pos, nxt):
            score += 1_000
        if must_vacate:
            score -= 150
        score += _tie_breaker(observation, action, nxt)

        if score < best_score:
            best_score = score
            best_action = action

    return best_action


def _would_edge_swap(
    pos: tuple[int, int],
    nxt: tuple[int, int],
) -> bool:
    for start, dest in _moves.values():
        if start == nxt and dest == pos:
            return True
    return False


def _tie_breaker(
    observation: Observation,
    action: Action,
    nxt: tuple[int, int],
) -> int:
    action_rank = {
        Action.RIGHT: 0,
        Action.DOWN: 1,
        Action.LEFT: 2,
        Action.UP: 3,
    }[action]
    return (
        observation.robot_id * 17
        + observation.tick * 5
        + nxt[0] * 3
        + nxt[1] * 7
        + action_rank
    ) % 17
