# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 16
# job:        9686b7a8fc67  (https://refugio-hackathon-nine.vercel.app/jobs/9686b7a8fc67)
# deliveries: 824    points: 0    runtime: 36.28s
# submitted:  2026-06-27 10:45:56.713 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/9686b7a8fc67    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0824__equipo-16__9686b7a8fc67.py --count 20
# ===========================================================================

"""REFUGIO Warehouse Challenge — congestion-aware routing with intra-tick reservations.

Two required entry points (loaded by warehouse.submission_loader):

  * create_layout() -> dict   : the static 960-shelf warehouse map
  * act(observation) -> Action: one action for one robot on one tick

Approach
--------
Per tick the simulator calls act() once per robot, in robot_id order, so
robot_id acts as a fixed priority. We exploit that with a lightweight
*cooperative* scheme (the decentralized analog of prioritized / cooperative A*):

1. **Congestion-aware A*.**  Each robot plans a shortest path to its goal (a
   free cell beside the target shelf, or the base drop cell) with an A* whose
   step cost is ``1 + PENALTY * (robots adjacent to the entered cell)``. This
   steers traffic into the open 60%-empty parts of the map instead of letting
   everyone funnel down the same aisle — the single biggest throughput win over
   naive shortest-path routing.

2. **Intra-tick reservations.**  As each robot commits to a move it records, in
   module globals reset every tick, the cell it is *entering* (claimed) and the
   cell it is *leaving* (vacated). Lower-priority robots then:
     - never enter a cell a higher robot already claimed (no vertex conflict),
     - never swap through a higher robot (no edge swap), but
     - **may** move into a cell a higher robot is vacating this very tick.
   That last rule lets queues of robots flow forward as a train in a single
   tick, instead of treating every neighbour as a permanent wall and stalling.

The reservation table is the only cross-call state; it carries intent *within*
a tick and is wiped at each new tick, and the static path graph is a pure
function of the (unchanging) layout. The simulator's own collision resolver is
the safety net — any residual conflict simply reverts to WAIT, so imperfect
reservations cost throughput, never correctness.
"""

from __future__ import annotations

import heapq

from warehouse_api import Action, CellType, Observation, Position


# ---------------------------------------------------------------------------
# Layout
# ---------------------------------------------------------------------------

def create_layout() -> dict:
    """Canonical wide-avenue rack layout: 12 * 2 * 4 * 10 = 960 shelves.

    2-wide shelf columns every 4 cells (2-wide avenues between them) in four
    10-row bands with 2-wide cross-aisles. Bidirectional 2-wide avenues let the
    reservation logic route trains past oncoming traffic without head-on jams.
    """
    shelves: list[list[int]] = []
    for x0 in range(3, 48, 4):
        for y0, y1 in ((3, 12), (15, 24), (27, 36), (39, 48)):
            for x in (x0, x0 + 1):
                for y in range(y0, y1 + 1):
                    shelves.append([x, y])
    return {"schema_version": 1, "shelves": shelves}


# ---------------------------------------------------------------------------
# Static, layout-derived graph (built once; pure function of the grid)
# ---------------------------------------------------------------------------

_ACTION_DELTAS = (
    (Action.UP, (0, -1)),
    (Action.RIGHT, (1, 0)),
    (Action.DOWN, (0, 1)),
    (Action.LEFT, (-1, 0)),
)

# Extra cost (in path steps) for entering a cell that has a robot beside it.
# Tuned empirically on the public seeds; the 0.5-1.0 range is a flat plateau
# (~805-821 total), so this is robust rather than overfit.
PENALTY = 0.75

_PASSABLE: frozenset[Position] | None = None
_NEIGHBORS: dict[Position, tuple[tuple[Action, Position], ...]] | None = None


def _build_graph(grid) -> None:
    global _PASSABLE, _NEIGHBORS
    if _PASSABLE is not None:
        return
    passable = frozenset(
        (x, y)
        for y, row in enumerate(grid)
        for x, cell in enumerate(row)
        if cell == CellType.EMPTY
    )
    _PASSABLE = passable
    _NEIGHBORS = {
        pos: tuple(
            (action, (pos[0] + dx, pos[1] + dy))
            for action, (dx, dy) in _ACTION_DELTAS
            if (pos[0] + dx, pos[1] + dy) in passable
        )
        for pos in passable
    }


# ---------------------------------------------------------------------------
# Intra-tick reservation state (reset whenever the tick advances)
# ---------------------------------------------------------------------------

_TICK = -1
_CLAIMED: set[Position] = set()      # cells a higher-priority robot enters this tick
_VACATED: set[Position] = set()      # cells a higher-priority robot leaves this tick
_SWAPS: set[tuple[Position, Position]] = set()  # (start, dest) pairs that would swap


def _reset_tick(tick: int) -> None:
    global _TICK, _CLAIMED, _VACATED, _SWAPS
    _TICK = tick
    _CLAIMED = set()
    _VACATED = set()
    _SWAPS = set()


# ---------------------------------------------------------------------------
# Policy
# ---------------------------------------------------------------------------

def _adjacent(a: Position, b: Position) -> bool:
    return abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1


def _drop_cell_for_base(base: Position) -> Position:
    x, y = base
    if y == 0:
        return (x, 1)
    if y == 51:
        return (x, 50)
    if x == 0:
        return (1, y)
    return (50, y)


def act(observation: Observation) -> Action:
    if observation.tick != _TICK:
        _reset_tick(observation.tick)

    pos = observation.position

    # Interact the instant we're in position.
    if not observation.carrying_item and _adjacent(pos, observation.target_item_position):
        return Action.PICKUP
    drop_cell = _drop_cell_for_base(observation.base_position)
    if observation.carrying_item and pos == drop_cell:
        return Action.DROP

    _build_graph(observation.grid)

    occupied = {
        p for rid, p in observation.all_robot_positions.items()
        if rid != observation.robot_id
    }

    if observation.carrying_item:
        goals = frozenset((drop_cell,))
    else:
        tx, ty = observation.target_item_position
        pickup_cells = tuple(
            c for c in ((tx + 1, ty), (tx - 1, ty), (tx, ty + 1), (tx, ty - 1))
            if c in _PASSABLE
        )
        if not pickup_cells:
            return Action.WAIT
        goals = frozenset(pickup_cells)

    action, dest = _plan(pos, goals, occupied)
    if action is not None and dest != pos:
        _CLAIMED.add(dest)
        _VACATED.add(pos)
        _SWAPS.add((dest, pos))  # a later robot moving pos->dest' with start dest would swap
        return action
    return Action.WAIT


def _crowd(cell: Position, occupied: set[Position]) -> int:
    x, y = cell
    return (
        ((x + 1, y) in occupied)
        + ((x - 1, y) in occupied)
        + ((x, y + 1) in occupied)
        + ((x, y - 1) in occupied)
    )


def _plan(start: Position, goals: frozenset[Position], occupied: set[Position]):
    """A* to the nearest goal.

    The *first* step must be reservation-safe (not entering an occupied cell
    unless a higher robot is vacating it, not a claimed cell, not a swap). Deeper
    along the path other robots are treated as soft cost only, so the heading
    stays direct while still skirting crowds. Returns (action, dest_cell), or
    (None, start) if no move helps.
    """
    if start in goals:
        return None, start

    # Cells we may not step into this tick.
    blocked_first = (occupied - _VACATED) | _CLAIMED

    def h(cell: Position) -> int:
        x, y = cell
        return min(abs(x - gx) + abs(y - gy) for gx, gy in goals)

    best_cost: dict[Position, float] = {start: 0.0}
    first_move: dict[Position, tuple[Action, Position]] = {start: (None, start)}
    frontier: list[tuple[float, float, Position]] = [(h(start), 0.0, start)]

    while frontier:
        _f, g, cell = heapq.heappop(frontier)
        if g > best_cost.get(cell, 1e18):
            continue
        if cell in goals:
            return first_move[cell]
        for action, nxt in _NEIGHBORS[cell]:
            if cell == start:
                if nxt in blocked_first or (start, nxt) in _SWAPS:
                    continue
            new_g = g + 1.0 + PENALTY * _crowd(nxt, occupied)
            if new_g < best_cost.get(nxt, 1e18):
                best_cost[nxt] = new_g
                first_move[nxt] = (action, nxt) if cell == start else first_move[cell]
                heapq.heappush(frontier, (new_g + h(nxt), new_g, nxt))

    return None, start
