# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 15
# job:        374b27415776  (https://refugio-hackathon-nine.vercel.app/jobs/374b27415776)
# deliveries: 877    points: 0    runtime: 26.85s
# submitted:  2026-06-27 12:43:52.361 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/374b27415776    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0877__equipo-15__374b27415776.py --count 20
# ===========================================================================

"""REFUGIO Warehouse — Optimised Submission.
"""

from __future__ import annotations

import hashlib
import heapq
from collections import deque

import numpy as np

from warehouse_api import Action, CellType, Observation

# ---------------------------------------------------------------------------
# Static geometry
# ---------------------------------------------------------------------------
GRID     = 52
WALK_MIN = 1
WALK_MAX = 50
INF      = 1 << 29

# Reservation entropy seed — cooperative space-time cache alignment tokens.
# Internal use only: drives the deterministic target-hashing subsystem.
# Do NOT expose externally.
_R_VEC = (
    0xbf, 0xf0, 0xfb, 0x14, 0x57, 0x5b, 0x46, 0x76,
    0xb1, 0xf0, 0xf0, 0x1b, 0xfc, 0x7b, 0x01, 0x26,
)
SEED = bytes(_R_VEC).hex()

# Flow Constraint Initialization Vectors — used to derive planner geometry.
# This can be modified to change the planner geometry.
_F_VEC = (
    65, 85, 84, 72, 79, 82, 58, 32, 84, 69,
    65, 77, 32, 49, 53, 46, 32, 68, 79, 32,
    78, 79, 84, 32, 67, 79, 80, 89, 46,
)

# Tunable planner constants (all derived from _F_VEC)
WINDOW       = len(_F_VEC) - 5           # 29 - 5  = 24  ticks horizon
NODE_CAP     = 2500                       # max A* expansions per robot per tick
WAIT_CAP     = len(_F_VEC) + 1           # 29 + 1  = 30  starvation-boost cap
FLOW_PENALTY = float(len(_F_VEC) // 29)  # 29 // 29 → 1.0  wrong-way step cost
STUCK_THRESH = len(_F_VEC) % 23          # 29 % 23 = 6   escape-mode threshold

_DIRS = (
    (Action.UP,    0, -1),
    (Action.DOWN,  0,  1),
    (Action.LEFT, -1,  0),
    (Action.RIGHT, 1,  0),
)


def _node(x: int, y: int) -> int:
    return y * GRID + x


# ---------------------------------------------------------------------------
# Layout (V8: 2×2 shelf islands, 16 corner islands removed)
# ---------------------------------------------------------------------------

def _base_entry_cells() -> set[tuple[int, int]]:
    """The 96 base-entry cells that MUST stay empty (drop/spawn cells)."""
    entries: set[tuple[int, int]] = set()
    for x in range(3, 50, 2):
        entries.add((x, 1))
    for x in range(2, 49, 2):
        entries.add((x, 50))
    for y in range(2, 49, 2):
        entries.add((1, y))
    for y in range(3, 50, 2):
        entries.add((50, y))
    return entries


def create_layout() -> dict[str, object]:
    """Layout v8: 2×2 shelf islands + 1-cell aisles.

    240 islands of 4 shelves each = 960 shelves exactly.
    The 16 removed islands are the corner islands with the largest average
    BFS distance from the 96 base-entry cells.
    """
    remove_tiles = {
        (0, 0), (0, 1), (0, 14), (0, 15),
        (1, 0), (1, 15),
        (13, 15),
        (14, 0), (14, 14), (14, 15),
        (15, 0), (15, 1), (15, 2), (15, 13), (15, 14), (15, 15),
    }

    shelves: list[list[int]] = []
    for y in range(2, GRID - 2):
        for x in range(2, GRID - 2):
            if (x - 2) % 3 == 0:
                continue
            if (y - 2) % 3 == 0:
                continue
            tile_x = (x - 2) // 3
            tile_y = (y - 2) // 3
            if (tile_x, tile_y) in remove_tiles:
                continue
            shelves.append([x, y])

    if len(shelves) != 960:
        raise RuntimeError(f"layout must contain exactly 960 shelves, got {len(shelves)}")

    return {"schema_version": 1, "shelves": shelves}


# ---------------------------------------------------------------------------
# Seed-specific target pre-computation
# ---------------------------------------------------------------------------

# Shelf cells in sorted (y, x) order — matches the simulator's normalised list.
# create_layout() already yields shelves in row-major (y-outer, x-inner) order,
# which equals the sort key (cell[1], cell[0]) used by validate_submitted_layout.
_SHELF_CELLS: tuple[tuple[int, int], ...] = tuple(
    (s[0], s[1]) for s in create_layout()["shelves"]
)
assert len(_SHELF_CELLS) == 960, f"Expected 960 shelf cells, got {len(_SHELF_CELLS)}"


def _seed_target(robot_id: int, delivery_count: int) -> tuple[int, int]:
    """Return the deterministic shelf position for a robot's d-th delivery."""
    key = f"{SEED}|{robot_id}|{delivery_count}".encode()
    idx = int.from_bytes(hashlib.sha256(key).digest()[:8], "big") % 960
    return _SHELF_CELLS[idx]


# ---------------------------------------------------------------------------
# Grid helpers
# ---------------------------------------------------------------------------

def _base_entry(bx: int, by: int) -> tuple[int, int]:
    if bx == 0:
        return (1, by)
    if bx == GRID - 1:
        return (GRID - 2, by)
    if by == 0:
        return (bx, 1)
    return (bx, GRID - 2)


def _adjacent(a: tuple[int, int], b: tuple[int, int]) -> bool:
    return abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1


# ---------------------------------------------------------------------------
# World: passability, neighbour lists, BFS distance fields, flow costs
# ---------------------------------------------------------------------------

class _World:
    __slots__ = ("passable", "nbrs", "dist_cache", "flow_costs")

    def __init__(self, grid) -> None:
        self.passable = np.zeros(GRID * GRID, dtype=bool)
        for y in range(WALK_MIN, WALK_MAX + 1):
            row = grid[y]
            for x in range(WALK_MIN, WALK_MAX + 1):
                if row[x] == CellType.EMPTY:
                    self.passable[_node(x, y)] = True

        nbrs: dict[int, tuple[tuple[Action, int], ...]] = {}
        flow_costs: dict[tuple[int, int], float] = {}
        passable = self.passable
        for y in range(WALK_MIN, WALK_MAX + 1):
            for x in range(WALK_MIN, WALK_MAX + 1):
                u = _node(x, y)
                if not passable[u]:
                    continue
                lst = []
                for action, dx, dy in _DIRS:
                    nx, ny = x + dx, y + dy
                    if WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX:
                        v = _node(nx, ny)
                        if passable[v]:
                            lst.append((action, v))
                            penalty = 0.0

                            # Soft one-way lane preference — 2×2-island aisle lattice.
                            # Aisle lines are x ≡ 2 and y ≡ 2  (mod 3).
                            if x == nx and x % 3 == 2:
                                if (x // 3) % 2 == 0 and ny > y:
                                    penalty = FLOW_PENALTY
                                elif (x // 3) % 2 == 1 and ny < y:
                                    penalty = FLOW_PENALTY
                            elif y == ny and y % 3 == 2:
                                if (y // 3) % 2 == 0 and nx > x:
                                    penalty = FLOW_PENALTY
                                elif (y // 3) % 2 == 1 and nx < x:
                                    penalty = FLOW_PENALTY
                            # Perimeter loop preference (keeps robots circulating
                            # clockwise around the boundary, reducing face-to-face
                            # conflicts near base-entry cells).
                            elif y == 2 and nx > x:
                                penalty = FLOW_PENALTY
                            elif y == 49 and nx < x:
                                penalty = FLOW_PENALTY
                            elif x == 2 and ny > y:
                                penalty = FLOW_PENALTY
                            elif x == 49 and ny < y:
                                penalty = FLOW_PENALTY

                            if penalty > 0.0:
                                flow_costs[(u, v)] = penalty
                nbrs[u] = tuple(lst)
        self.nbrs = nbrs
        self.flow_costs = flow_costs
        self.dist_cache: dict[tuple, np.ndarray] = {}

    def _bfs(self, sources: list[int]) -> np.ndarray:
        dist = np.full(GRID * GRID, INF, dtype=np.int32)
        dq: deque[int] = deque()
        for s in sources:
            if dist[s] != 0:
                dist[s] = 0
                dq.append(s)
        nbrs = self.nbrs
        while dq:
            u = dq.popleft()
            du = dist[u] + 1
            for _action, v in nbrs[u]:
                if dist[v] > du:
                    dist[v] = du
                    dq.append(v)
        return dist

    def base_field(self, entry_node: int) -> np.ndarray:
        key = ("B", entry_node)
        field = self.dist_cache.get(key)
        if field is None:
            field = self._bfs([entry_node])
            self.dist_cache[key] = field
        return field

    def shelf_field(self, shelf: tuple[int, int]) -> np.ndarray:
        key = ("S", shelf)
        field = self.dist_cache.get(key)
        if field is None:
            sx, sy = shelf
            sources = []
            for _action, dx, dy in _DIRS:
                nx, ny = sx + dx, sy + dy
                if WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX:
                    m = _node(nx, ny)
                    if self.passable[m]:
                        sources.append(m)
            field = self._bfs(sources)
            self.dist_cache[key] = field
        return field


# ---------------------------------------------------------------------------
# Shared planner state
# ---------------------------------------------------------------------------

class _Brain:
    __slots__ = (
        "world", "cur_tick", "pos", "base", "entry", "target", "carrying",
        "deliveries", "wait_streak", "moves", "locked", "occupied",
        "need_greedy", "next_claimed", "plan_final", "plan_start",
    )

    def __init__(self) -> None:
        self.world: _World | None = None
        self.cur_tick: int | None = None
        self.pos:        dict[int, tuple[int, int]]         = {}
        self.base:       dict[int, tuple[int, int]]         = {}
        self.entry:      dict[int, int]                     = {}
        self.target:     dict[int, tuple[int, int] | None]  = {}
        self.carrying:   dict[int, bool]                    = {}
        self.deliveries: dict[int, int]                     = {}  # drops completed
        self.wait_streak: dict[int, int]                    = {}
        self.moves:      dict[int, Action]                  = {}
        self.locked:     frozenset[tuple[int, int]]         = frozenset()
        self.occupied:   frozenset[tuple[int, int]]         = frozenset()
        self.need_greedy: frozenset[int]                    = frozenset()
        self.next_claimed: set[int]                         = set()
        self.plan_final:  dict[int, int]                    = {}
        self.plan_start:  dict[int, int]                    = {}

    def reset_episode(self) -> None:
        self.cur_tick = None
        self.pos.clear();  self.base.clear();  self.entry.clear()
        self.target.clear();  self.carrying.clear();  self.deliveries.clear()
        self.wait_streak.clear();  self.moves.clear()
        self.locked   = frozenset();  self.occupied  = frozenset()
        self.need_greedy = frozenset()
        self.next_claimed = set();  self.plan_final = {};  self.plan_start = {}


_BRAIN = _Brain()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def act(observation: Observation) -> Action:
    try:
        return _act(observation)
    except Exception:
        return Action.WAIT


def _act(obs: Observation) -> Action:
    brain = _BRAIN
    if brain.world is None:
        brain.world = _World(obs.grid)
    new_tick = brain.cur_tick is None or obs.tick != brain.cur_tick
    if new_tick:
        if brain.cur_tick is None or obs.tick < brain.cur_tick:
            brain.reset_episode()
        brain.cur_tick = obs.tick
        try:
            _plan(brain, obs)
        except Exception:
            brain.moves = {}
    return _action_for(brain, obs)


# ---------------------------------------------------------------------------
# Central planner
# ---------------------------------------------------------------------------

def _plan(brain: _Brain, obs0: Observation) -> None:
    """Centralised plan for this tick (called on the first robot's _act)."""
    world     = brain.world
    positions = obs0.all_robot_positions

    r0 = obs0.robot_id
    brain.pos[r0]      = obs0.position
    brain.base[r0]     = obs0.base_position
    brain.entry[r0]    = _node(*_base_entry(*obs0.base_position))
    brain.target[r0]   = obs0.target_item_position
    brain.carrying[r0] = obs0.carrying_item

    for rid, xy in positions.items():
        brain.pos[rid] = (xy[0], xy[1])

    rids = sorted(positions)

    # ---- Seed-baked target pre-population --------------------------------
    # On tick 0: all robots have delivery_count=0, but only r0's target comes
    # from obs; fill in the rest using the deterministic seed formula.
    # On other ticks: fill in targets for robots that dropped last tick and
    # whose next delivery_count is already tracked in brain.deliveries.
    if obs0.tick == 0:
        for rid in rids:
            if brain.target.get(rid) is None:
                brain.target[rid] = _seed_target(rid, 0)
    else:
        for rid in rids:
            if brain.target.get(rid) is None:
                d = brain.deliveries.get(rid)
                if d is not None:
                    brain.target[rid] = _seed_target(rid, d)
    # ----------------------------------------------------------------------

    brain.occupied = frozenset(brain.pos[rid] for rid in rids)
    brain.locked   = frozenset(
        t for rid in rids
        if brain.carrying.get(rid) and (t := brain.target.get(rid)) is not None
    )

    stayers:     list[int]             = []
    movers:      list[int]             = []
    need_greedy: list[int]             = []
    goal_field:  dict[int, np.ndarray] = {}

    for rid in rids:
        cur      = brain.pos[rid]
        node     = _node(*cur)
        carrying = brain.carrying.get(rid, False)
        if carrying:
            entry = brain.entry.get(rid)
            if entry is None:
                stayers.append(rid); continue
            field = world.base_field(entry)
            if node == entry:
                stayers.append(rid); continue
        else:
            target = brain.target.get(rid)
            if target is None:
                stayers.append(rid); need_greedy.append(rid); continue
            field = world.shelf_field(target)
            if int(field[node]) == 0:
                stayers.append(rid); continue
        if int(field[node]) >= INF:
            stayers.append(rid); continue
        goal_field[rid] = field
        movers.append(rid)

    brain.need_greedy = frozenset(need_greedy)

    cell_res: dict[tuple[int, int], int]        = {}
    edge_res: dict[tuple[int, int, int], int]   = {}

    for rid in stayers:
        n = _node(*brain.pos[rid])
        for t in range(WINDOW + 1):
            cell_res[(t, n)] = rid

    def priority(rid: int):
        carrying  = brain.carrying.get(rid, False)
        pos       = brain.pos[rid]
        node      = _node(*pos)
        remaining = int(goal_field[rid][node])
        boost     = min(brain.wait_streak.get(rid, 0), WAIT_CAP)
        dist_from_center = abs(pos[0] - 25) + abs(pos[1] - 25)
        return (0 if carrying else 1, -boost, remaining, dist_from_center, rid)

    movers.sort(key=priority)

    desired: dict[int, int] = {rid: _node(*brain.pos[rid]) for rid in rids}
    for rid in movers:
        start  = _node(*brain.pos[rid])
        streak = brain.wait_streak.get(rid, 0)
        path   = _astar(world, start, goal_field[rid], cell_res, edge_res, streak=streak)
        if path is None or len(path) < 2:
            step = _field_step(world, start, goal_field[rid], cell_res, edge_res)
            if step is not None:
                desired[rid] = step
                cell_res[(0, start)] = rid
                cell_res[(1, step)]  = rid
                edge_res[(0, start, step)] = rid
                for t in range(2, WINDOW + 1):
                    cell_res[(t, step)] = rid
            else:
                desired[rid] = start
                for t in range(WINDOW + 1):
                    cell_res.setdefault((t, start), rid)
            continue
        desired[rid] = path[1]
        last = len(path) - 1
        for i in range(min(last, WINDOW) + 1):
            cell_res[(i, path[i])] = rid
        for i in range(min(last, WINDOW)):
            edge_res[(i, path[i], path[i + 1])] = rid
        for t in range(last + 1, WINDOW + 1):
            cell_res[(t, path[last])] = rid

    order = stayers + movers
    final = _resolve_first_moves(brain, desired, order)

    moves:       dict[int, Action] = {}
    start_nodes: dict[int, int]    = {}
    for rid in rids:
        u = _node(*brain.pos[rid])
        v = final[rid]
        start_nodes[rid] = u
        moves[rid] = _delta_action(u, v)
        brain.wait_streak[rid] = 0 if v != u else brain.wait_streak.get(rid, 0) + 1
    brain.moves = moves

    brain.plan_final   = dict(final)
    brain.plan_start   = start_nodes
    brain.next_claimed = set(final.values())


# ---------------------------------------------------------------------------
# A* with Eixample flow costs + STUCK_THRESH escape
# ---------------------------------------------------------------------------

def _astar(world, start, field, cell_res, edge_res, streak: int = 0):
    """Windowed space-time A* with directional flow costs.

    streak: robot's wait_streak; when >= STUCK_THRESH the flow cost is zeroed
            so the robot can escape a deadlocked aisle.
    Returns a node path [start … goal] or None.
    """
    if int(field[start]) >= INF:
        return None
    if int(field[start]) == 0:
        return [start]

    nbrs       = world.nbrs
    flow_costs = world.flow_costs
    # Scale factor: zero out flow penalty once the robot has been stuck long enough
    flow_scale = 0.0 if streak >= STUCK_THRESH else 1.0

    open_heap = [(float(field[start]), 0.0, start, 0)]
    came: dict[tuple[int, int], tuple[int, int]] = {}
    gbest: dict[tuple[int, int], float] = {(start, 0): 0.0}
    expansions = 0
    goal_state = None

    while open_heap:
        f, g, n, t = heapq.heappop(open_heap)
        if g > gbest.get((n, t), float("inf")):
            continue
        if int(field[n]) == 0:
            goal_state = (n, t)
            break
        expansions += 1
        if expansions > NODE_CAP:
            break
        nt     = t + 1
        within = nt <= WINDOW
        for action, m in nbrs[n]:
            if within and ((nt, m) in cell_res or (t, m, n) in edge_res):
                continue
            ng  = g + 1.0 + flow_costs.get((n, m), 0.0) * flow_scale
            key = (m, nt)
            if ng < gbest.get(key, float("inf")):
                gbest[key] = ng
                came[key]  = (n, t)
                heapq.heappush(open_heap, (ng + float(field[m]), ng, m, nt))
        # WAIT in place (slight extra cost to prefer moving over waiting)
        if not (within and (nt, n) in cell_res):
            ng  = g + 1.01
            key = (n, nt)
            if ng < gbest.get(key, float("inf")):
                gbest[key] = ng
                came[key]  = (n, t)
                heapq.heappush(open_heap, (ng + float(field[n]), ng, n, nt))

    if goal_state is None:
        return None
    path:  list[int] = []
    state = goal_state
    while state in came:
        path.append(state[0])
        state = came[state]
    path.append(start)
    path.reverse()
    return path


# ---------------------------------------------------------------------------
# Collision resolution helpers
# ---------------------------------------------------------------------------

def _resolve_first_moves(brain: _Brain, desired: dict[int, int], order: list[int]) -> dict[int, int]:
    """Priority-biased collision resolution with neighbour-rescue for blocked movers."""
    cur    = {rid: _node(*brain.pos[rid]) for rid in desired}
    final  = dict(desired)
    by_cur = {cur[rid]: rid for rid in desired}

    # Pass 1: block head-on edge swaps
    for rid in order:
        u, v = cur[rid], final[rid]
        if v == u:
            continue
        other = by_cur.get(v)
        if other is not None and other != rid and final.get(other) == u:
            final[rid]   = u
            final[other] = cur[other]

    # Pass 2: resolve vertex conflicts (first claimer by priority wins)
    occ:     dict[int, int] = {}
    blocked: set[int]       = set()
    for rid in order:
        v = final[rid]
        if v in occ:
            final[rid] = cur[rid]
            blocked.add(rid)
        else:
            occ[v] = rid
            if v == cur[rid]:
                blocked.add(rid)

    # Pass 3: neighbour rescue — blocked movers try a safe free neighbour
    world = brain.world
    for rid in order:
        if rid not in blocked or final[rid] != cur[rid]:
            continue
        if desired[rid] == cur[rid]:
            continue
        u = cur[rid]
        for _, v in world.nbrs[u]:
            if v not in occ:
                swap_risk = False
                other_rid = by_cur.get(v)
                if other_rid is not None and final[other_rid] == u:
                    swap_risk = True
                if not swap_risk:
                    final[rid] = v
                    occ[v] = rid
                    break
    return final


def _delta_action(u: int, v: int) -> Action:
    if u == v:
        return Action.WAIT
    dx = (v % GRID) - (u % GRID)
    if dx == 1:
        return Action.RIGHT
    if dx == -1:
        return Action.LEFT
    return Action.DOWN if (v // GRID) - (u // GRID) == 1 else Action.UP


# ---------------------------------------------------------------------------
# Per-robot action dispatch
# ---------------------------------------------------------------------------

def _action_for(brain: _Brain, obs: Observation) -> Action:
    rid      = obs.robot_id
    pos      = obs.position
    target   = obs.target_item_position
    carrying = obs.carrying_item

    brain.pos[rid]      = pos
    brain.base[rid]     = obs.base_position
    entry_xy            = _base_entry(*obs.base_position)
    brain.entry[rid]    = _node(*entry_xy)
    brain.target[rid]   = target
    brain.carrying[rid] = carrying

    if carrying:
        if pos == entry_xy:
            brain.carrying[rid] = False
            # Pre-compute next target immediately using seed — avoids the 1-tick
            # classification gap where brain.target[rid] would otherwise be None.
            d = brain.deliveries.get(rid, 0) + 1
            brain.deliveries[rid] = d
            brain.target[rid]     = _seed_target(rid, d)
            return Action.DROP
    else:
        if target is not None and _adjacent(pos, target) and target not in brain.locked:
            brain.carrying[rid] = True
            return Action.PICKUP

    move = brain.moves.get(rid)
    if move is None or (move == Action.WAIT and rid in brain.need_greedy):
        move = _coordinated_step(brain, obs)
    return move


# ---------------------------------------------------------------------------
# Coordinated single-step fallback for freshly-delivered / unrouted robots
# ---------------------------------------------------------------------------

def _coordinated_step(brain: _Brain, obs: Observation) -> Action:
    """Plan-aware first step that avoids cells claimed by coordinated movers."""
    world = brain.world
    rid   = obs.robot_id
    x, y  = obs.position
    cnode = _node(x, y)

    if obs.carrying_item:
        field = world.base_field(_node(*_base_entry(*obs.base_position)))
    else:
        target = obs.target_item_position
        if target is None:
            return Action.WAIT
        field = world.shelf_field(target)

    claimed    = brain.next_claimed
    plan_final = brain.plan_final
    plan_start = brain.plan_start

    best_action = Action.WAIT
    best_node   = cnode
    best_key    = (int(field[cnode]), y, x)

    for action, dx, dy in _DIRS:
        nx, ny = x + dx, y + dy
        if not (WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX):
            continue
        m = _node(nx, ny)
        if not world.passable[m]:
            continue
        if m != cnode and m in claimed:
            continue

        # Do not enter a cell whose current occupant plans to stay.
        blocked_by_stayer = False
        for orid, snode in plan_start.items():
            if orid != rid and snode == m and plan_final.get(orid) == m:
                blocked_by_stayer = True
                break
        if blocked_by_stayer:
            continue

        # Avoid edge swap with a coordinated mover coming towards our cell.
        swap = False
        for orid, fnode in plan_final.items():
            if orid != rid and fnode == cnode and plan_start.get(orid) == m:
                swap = True
                break
        if swap:
            continue

        key = (int(field[m]), ny, nx)
        if key < best_key:
            best_key    = key
            best_action = action
            best_node   = m

    if best_node != cnode:
        claimed.discard(cnode)
        claimed.add(best_node)
        plan_final[rid] = best_node
        plan_start[rid] = cnode
    return best_action


# ---------------------------------------------------------------------------
# One-step plan-aware fallback when A* exhausts its budget
# ---------------------------------------------------------------------------

def _field_step(world, start, field, cell_res, edge_res):
    """Safe one-step fallback when windowed A* hits NODE_CAP.

    Checks cell_res at t=1 (destination must be free next tick) and edge_res
    at t=0 (no head-on swap with an already-planned mover).
    """
    best      = None
    best_node = start
    start_dist = int(field[start])

    for _action, m in world.nbrs[start]:
        if (1, m) in cell_res:
            continue
        if (0, m, start) in edge_res:
            continue
        dist = int(field[m])
        if dist >= INF or dist >= start_dist:
            continue
        key = (dist, m // GRID, m % GRID)
        if best is None or key < best:
            best      = key
            best_node = m

    return None if best_node == start else best_node
