# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 04
# job:        3b8bedf4c0df  (https://refugio-hackathon-nine.vercel.app/jobs/3b8bedf4c0df)
# deliveries: 879    points: 0    runtime: 15.89s
# submitted:  2026-06-27 10:48:42.583 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/3b8bedf4c0df    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0879__equipo-04__3b8bedf4c0df.py --count 20
# ===========================================================================

"""REFUGIO Warehouse Challenge submission.

Centralized cooperative multi-agent pathfinding for 96 warehouse robots.

A single `act()` controls every robot. The simulator calls `act()` once per
robot per tick (robot 0..95) and module globals persist across ticks and seeds,
so this runs one centralized planner per tick on the first robot call and serves
the resulting move to every robot. Pathing is windowed prioritized cooperative
A* with space-time reservations, plus a final conflict-resolution pass that
mirrors the simulator's collision rules but lets higher-priority robots win
instead of reverting both.
"""

from __future__ import annotations

import heapq
from collections import deque

import numpy as np

from warehouse_api import Action, CellType, Observation


GRID = 52
WALK_MIN = 1
WALK_MAX = 50
INF = 1 << 29

WINDOW = 16
NODE_CAP = 1200
WAIT_CAP = 25

DIRECTIONS = (
    (Action.UP, 0, -1),
    (Action.DOWN, 0, 1),
    (Action.LEFT, -1, 0),
    (Action.RIGHT, 1, 0),
)


def node(x: int, y: int) -> int:
    return y * GRID + x


def create_layout() -> dict[str, object]:
    """Return the canonical 960-shelf rack-block layout."""
    shelves: list[list[int]] = []
    for x0 in range(3, 48, 4):
        for y0, y1 in ((3, 12), (15, 24), (27, 36), (39, 48)):
            for x in (x0, x0 + 1):
                for y in range(y0, y1 + 1):
                    shelves.append([x, y])
    return {"schema_version": 1, "shelves": shelves}


def base_entry(bx: int, by: int) -> tuple[int, int]:
    """Walkable interior cell adjacent to an external base."""
    if bx == 0:
        return (1, by)
    if bx == GRID - 1:
        return (GRID - 2, by)
    if by == 0:
        return (bx, 1)
    return (bx, GRID - 2)


def adjacent(a: tuple[int, int], b: tuple[int, int]) -> bool:
    return abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1


class World:
    """Static grid structures: passable mask, neighbor lists, distance cache."""

    __slots__ = ("passable", "neighbors", "dist_cache")

    def __init__(self, grid) -> None:
        self.passable = np.zeros(GRID * GRID, dtype=bool)
        for y in range(WALK_MIN, WALK_MAX + 1):
            row = grid[y]
            for x in range(WALK_MIN, WALK_MAX + 1):
                if row[x] == CellType.EMPTY:
                    self.passable[node(x, y)] = True

        neighbors: dict[int, tuple[tuple[Action, int], ...]] = {}
        passable = self.passable
        for y in range(WALK_MIN, WALK_MAX + 1):
            for x in range(WALK_MIN, WALK_MAX + 1):
                current = node(x, y)
                if not passable[current]:
                    continue
                candidates = []
                for action, dx, dy in DIRECTIONS:
                    nx, ny = x + dx, y + dy
                    if WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX:
                        candidate = node(nx, ny)
                        if passable[candidate]:
                            candidates.append((action, candidate))
                neighbors[current] = tuple(candidates)
        self.neighbors = neighbors
        self.dist_cache: dict[tuple, np.ndarray] = {}

    def bfs(self, sources: list[int]) -> np.ndarray:
        distances = np.full(GRID * GRID, INF, dtype=np.int32)
        queue: deque[int] = deque()
        for source in sources:
            if distances[source] != 0:
                distances[source] = 0
                queue.append(source)
        neighbors = self.neighbors
        while queue:
            current = queue.popleft()
            next_distance = distances[current] + 1
            for _action, candidate in neighbors[current]:
                if distances[candidate] > next_distance:
                    distances[candidate] = next_distance
                    queue.append(candidate)
        return distances

    def base_field(self, entry_node: int) -> np.ndarray:
        key = ("B", entry_node)
        field = self.dist_cache.get(key)
        if field is None:
            field = self.bfs([entry_node])
            self.dist_cache[key] = field
        return field

    def shelf_field(self, shelf: tuple[int, int]) -> np.ndarray:
        key = ("S", shelf)
        field = self.dist_cache.get(key)
        if field is None:
            sx, sy = shelf
            sources = []
            for _action, dx, dy in DIRECTIONS:
                nx, ny = sx + dx, sy + dy
                if WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX:
                    candidate = node(nx, ny)
                    if self.passable[candidate]:
                        sources.append(candidate)
            field = self.bfs(sources)
            self.dist_cache[key] = field
        return field


class Brain:
    """Dynamic per-episode planner state shared across all robots."""

    __slots__ = (
        "world",
        "cur_tick",
        "pos",
        "base",
        "entry",
        "target",
        "carrying",
        "wait_streak",
        "moves",
        "locked",
        "occupied",
        "need_greedy",
    )

    def __init__(self) -> None:
        self.world: World | None = None
        self.cur_tick: int | None = None
        self.pos: dict[int, tuple[int, int]] = {}
        self.base: dict[int, tuple[int, int]] = {}
        self.entry: dict[int, int] = {}
        self.target: dict[int, tuple[int, int] | None] = {}
        self.carrying: dict[int, bool] = {}
        self.wait_streak: dict[int, int] = {}
        self.moves: dict[int, Action] = {}
        self.locked: frozenset[tuple[int, int]] = frozenset()
        self.occupied: frozenset[tuple[int, int]] = frozenset()
        self.need_greedy: frozenset[int] = frozenset()

    def reset_episode(self) -> None:
        self.cur_tick = None
        self.pos.clear()
        self.base.clear()
        self.entry.clear()
        self.target.clear()
        self.carrying.clear()
        self.wait_streak.clear()
        self.moves.clear()
        self.locked = frozenset()
        self.occupied = frozenset()
        self.need_greedy = frozenset()


BRAIN = Brain()


def act(observation: Observation) -> Action:
    try:
        return act_inner(observation)
    except Exception:
        return Action.WAIT


def act_inner(observation: Observation) -> Action:
    brain = BRAIN
    if brain.world is None:
        brain.world = World(observation.grid)

    new_tick = brain.cur_tick is None or observation.tick != brain.cur_tick
    if new_tick:
        if brain.cur_tick is None or observation.tick < brain.cur_tick:
            brain.reset_episode()
        brain.cur_tick = observation.tick
        try:
            plan_tick(brain, observation)
        except Exception:
            brain.moves = {}

    return action_for(brain, observation)


def plan_tick(brain: Brain, first_observation: Observation) -> None:
    """Run the centralized plan for this tick."""
    world = brain.world
    positions = first_observation.all_robot_positions

    first_robot = first_observation.robot_id
    brain.pos[first_robot] = first_observation.position
    brain.base[first_robot] = first_observation.base_position
    brain.entry[first_robot] = node(*base_entry(*first_observation.base_position))
    brain.target[first_robot] = first_observation.target_item_position
    brain.carrying[first_robot] = first_observation.carrying_item

    for robot_id, position in positions.items():
        brain.pos[robot_id] = (position[0], position[1])

    robot_ids = sorted(positions)
    brain.occupied = frozenset(brain.pos[robot_id] for robot_id in robot_ids)
    brain.locked = frozenset(
        target
        for robot_id in robot_ids
        if brain.carrying.get(robot_id)
        and (target := brain.target.get(robot_id)) is not None
    )

    stayers: list[int] = []
    movers: list[int] = []
    need_greedy: list[int] = []
    goal_field: dict[int, np.ndarray] = {}

    for robot_id in robot_ids:
        current_position = brain.pos[robot_id]
        current_node = node(*current_position)
        carrying = brain.carrying.get(robot_id, False)

        if carrying:
            entry = brain.entry.get(robot_id)
            if entry is None:
                stayers.append(robot_id)
                continue
            field = world.base_field(entry)
            if current_node == entry:
                stayers.append(robot_id)
                continue
        else:
            target = brain.target.get(robot_id)
            if target is None:
                stayers.append(robot_id)
                need_greedy.append(robot_id)
                continue
            field = world.shelf_field(target)
            if int(field[current_node]) == 0:
                stayers.append(robot_id)
                continue

        if int(field[current_node]) >= INF:
            stayers.append(robot_id)
            continue

        goal_field[robot_id] = field
        movers.append(robot_id)

    brain.need_greedy = frozenset(need_greedy)

    cell_reservations: dict[tuple[int, int], int] = {}
    edge_reservations: dict[tuple[int, int, int], int] = {}

    for robot_id in stayers:
        current_node = node(*brain.pos[robot_id])
        for time_offset in range(WINDOW + 1):
            cell_reservations[(time_offset, current_node)] = robot_id

    def priority(robot_id: int) -> tuple[int, int, int, int]:
        carrying = brain.carrying.get(robot_id, False)
        current_node = node(*brain.pos[robot_id])
        remaining = int(goal_field[robot_id][current_node])
        boost = min(brain.wait_streak.get(robot_id, 0), WAIT_CAP)
        return (0 if carrying else 1, -boost, remaining, robot_id)

    movers.sort(key=priority)

    desired: dict[int, int] = {
        robot_id: node(*brain.pos[robot_id])
        for robot_id in robot_ids
    }
    for robot_id in movers:
        start = node(*brain.pos[robot_id])
        path = astar(world, start, goal_field[robot_id], cell_reservations, edge_reservations)
        if path is None or len(path) < 2:
            desired[robot_id] = start
            for time_offset in range(WINDOW + 1):
                cell_reservations.setdefault((time_offset, start), robot_id)
            continue

        desired[robot_id] = path[1]
        last = len(path) - 1
        for index in range(min(last, WINDOW) + 1):
            cell_reservations[(index, path[index])] = robot_id
        for index in range(min(last, WINDOW)):
            edge_reservations[(index, path[index], path[index + 1])] = robot_id
        for time_offset in range(last + 1, WINDOW + 1):
            cell_reservations[(time_offset, path[last])] = robot_id

    final = resolve_first_moves(brain, desired, stayers + movers)

    moves: dict[int, Action] = {}
    for robot_id in robot_ids:
        current = node(*brain.pos[robot_id])
        next_node = final[robot_id]
        moves[robot_id] = delta_action(current, next_node)
        brain.wait_streak[robot_id] = (
            0 if next_node != current else brain.wait_streak.get(robot_id, 0) + 1
        )
    brain.moves = moves


def astar(
    world: World,
    start: int,
    field: np.ndarray,
    cell_reservations: dict[tuple[int, int], int],
    edge_reservations: dict[tuple[int, int, int], int],
) -> list[int] | None:
    """Windowed space-time A*; returns a node path from start to goal."""
    if int(field[start]) >= INF:
        return None
    if int(field[start]) == 0:
        return [start]

    neighbors = world.neighbors
    open_heap = [(int(field[start]), 0, start, 0)]
    previous: dict[tuple[int, int], tuple[int, int]] = {}
    best_cost: dict[tuple[int, int], int] = {(start, 0): 0}
    expansions = 0
    goal_state = None

    while open_heap:
        _estimated, cost, current, time_offset = heapq.heappop(open_heap)
        if cost > best_cost.get((current, time_offset), INF):
            continue
        if int(field[current]) == 0:
            goal_state = (current, time_offset)
            break

        expansions += 1
        if expansions > NODE_CAP:
            break

        next_time = time_offset + 1
        within_window = next_time <= WINDOW
        next_cost = cost + 1

        for _action, candidate in neighbors[current]:
            if within_window and (
                (next_time, candidate) in cell_reservations
                or (time_offset, candidate, current) in edge_reservations
            ):
                continue
            key = (candidate, next_time)
            if next_cost < best_cost.get(key, INF):
                best_cost[key] = next_cost
                previous[key] = (current, time_offset)
                heapq.heappush(
                    open_heap,
                    (next_cost + int(field[candidate]), next_cost, candidate, next_time),
                )

        if not (within_window and (next_time, current) in cell_reservations):
            key = (current, next_time)
            if next_cost < best_cost.get(key, INF):
                best_cost[key] = next_cost
                previous[key] = (current, time_offset)
                heapq.heappush(
                    open_heap,
                    (next_cost + int(field[current]), next_cost, current, next_time),
                )

    if goal_state is None:
        return None

    path = []
    state = goal_state
    while state in previous:
        path.append(state[0])
        state = previous[state]
    path.append(start)
    path.reverse()
    return path


def resolve_first_moves(
    brain: Brain,
    desired: dict[int, int],
    order: list[int],
) -> dict[int, int]:
    """Priority-biased version of the simulator collision resolver."""
    current = {robot_id: node(*brain.pos[robot_id]) for robot_id in desired}
    final = dict(desired)
    current_occupant = {current[robot_id]: robot_id for robot_id in desired}

    for robot_id in order:
        current_node = current[robot_id]
        final_node = final[robot_id]
        if final_node == current_node:
            continue
        other = current_occupant.get(final_node)
        if other is not None and other != robot_id and final.get(other) == current_node:
            final[robot_id] = current_node
            final[other] = current[other]

    changed = True
    guard = 0
    while changed and guard < 256:
        changed = False
        guard += 1
        occupied: dict[int, int] = {}
        for robot_id in order:
            final_node = final[robot_id]
            if final_node in occupied:
                if final[robot_id] != current[robot_id]:
                    final[robot_id] = current[robot_id]
                    changed = True
            else:
                occupied[final_node] = robot_id
    return final


def delta_action(current: int, next_node: int) -> Action:
    if current == next_node:
        return Action.WAIT
    dx = (next_node % GRID) - (current % GRID)
    if dx == 1:
        return Action.RIGHT
    if dx == -1:
        return Action.LEFT
    return Action.DOWN if (next_node // GRID) - (current // GRID) == 1 else Action.UP


def action_for(brain: Brain, observation: Observation) -> Action:
    robot_id = observation.robot_id
    position = observation.position
    target = observation.target_item_position
    carrying = observation.carrying_item

    brain.pos[robot_id] = position
    brain.base[robot_id] = observation.base_position
    entry_position = base_entry(*observation.base_position)
    brain.entry[robot_id] = node(*entry_position)
    brain.target[robot_id] = target
    brain.carrying[robot_id] = carrying

    if carrying:
        if position == entry_position:
            brain.carrying[robot_id] = False
            brain.target[robot_id] = None
            return Action.DROP
    else:
        if adjacent(position, target) and target not in brain.locked:
            brain.carrying[robot_id] = True
            return Action.PICKUP

    move = brain.moves.get(robot_id)
    if move is None or (move == Action.WAIT and robot_id in brain.need_greedy):
        move = greedy_step(brain, observation)
    return move


def greedy_step(brain: Brain, observation: Observation) -> Action:
    world = brain.world
    x, y = observation.position
    if observation.carrying_item:
        field = world.base_field(node(*base_entry(*observation.base_position)))
    else:
        target = observation.target_item_position
        if target is None:
            return Action.WAIT
        field = world.shelf_field(target)

    occupied = brain.occupied
    best_action = Action.WAIT
    best_key = (int(field[node(x, y)]), y, x)
    for action, dx, dy in DIRECTIONS:
        nx, ny = x + dx, y + dy
        if not (WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX):
            continue
        candidate = node(nx, ny)
        if not world.passable[candidate] or (nx, ny) in occupied:
            continue
        key = (int(field[candidate]), ny, nx)
        if key < best_key:
            best_key = key
            best_action = action
    return best_action
