# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 14
# job:        27551e60ac6a  (https://refugio-hackathon-nine.vercel.app/jobs/27551e60ac6a)
# deliveries: 887    points: 0    runtime: 26.27s
# submitted:  2026-06-27 12:34:51.565 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/27551e60ac6a    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0887__equipo-14__27551e60ac6a.py --count 20
# ===========================================================================

import heapq
from collections import deque
import numpy as np

from warehouse_api import Action, CellType, Observation

# Grid size constants
GRID = 52
WALK_MIN = 1
WALK_MAX = 50
INF = 1000000.0  # Use float for weighted shortest path distances

# Tuned planner constants
WINDOW = 32
NODE_CAP = 3000
WAIT_CAP = 25
PENALTY = 0.1  # Soft direction penalty for Guidance Graph Optimization (GGO)

_DIRS = (
    (Action.UP, 0, -1),
    (Action.DOWN, 0, 1),
    (Action.LEFT, -1, 0),
    (Action.RIGHT, 1, 0),
)


def _node(x: int, y: int) -> int:
    return y * GRID + x


def _base_entry_cells() -> set[tuple[int, int]]:
    """Defines the set of external base entrance coordinates."""
    entries: set[tuple[int, int]] = set()
    for x in range(3, 50, 2):   # top
        entries.add((x, 1))
    for x in range(2, 49, 2):   # bottom
        entries.add((x, 50))
    for y in range(2, 49, 2):   # left
        entries.add((1, y))
    for y in range(3, 50, 2):   # right
        entries.add((50, y))
    return entries


def create_layout() -> dict[str, object]:
    """Highly-optimized 2x2 shelf block layout.

    By using 2x2 blocks of shelves separated by 1-cell aisles in both directions,
    there are frequent horizontal and vertical cross-aisles (every 2 shelf cells),
    drastically reducing traffic congestion and shortest-path detours.
    With margin=2, there is a wide perimeter loop for ultra-fast long-distance routing.
    Generates exactly 961 raw cells, leaving only 1 surplus shelf cell to be trimmed,
    resulting in a beautifully symmetric and uniform layout.
    """
    block_w, block_h, aisle_w, aisle_h, margin = 2, 2, 1, 1, 2
    lo, hi = 1 + margin, 50 - margin
    period_x, period_y = block_w + aisle_w, block_h + aisle_h

    cells: list[tuple[int, int]] = []
    x = lo
    while x <= hi:
        y = lo
        while y <= hi:
            for cx in range(x, min(x + block_w, hi + 1)):
                for cy in range(y, min(y + block_h, hi + 1)):
                    cells.append((cx, cy))
            y += period_y
        x += period_x

    entries = _base_entry_cells()
    cells = [c for c in cells if c not in entries]

    n = len(cells)
    extra = n - 960
    if extra > 0:
        removed: set[int] = set()
        for k in range(extra):
            idx = (k * n) // extra + n // (2 * extra)
            while idx in removed:
                idx = (idx + 1) % n
            removed.add(idx)
        cells = [c for i, c in enumerate(cells) if i not in removed]

    shelves: list[list[int]] = [[cx, cy] for (cx, cy) in cells]
    return {"schema_version": 1, "shelves": shelves}


def _base_entry(bx: int, by: int) -> tuple[int, int]:
    """Retrieves the walkable interior cell adjacent to an external base cell."""
    if bx == 0:
        return (1, by)
    if bx == GRID - 1:
        return (GRID - 2, by)
    if by == 0:
        return (bx, 1)
    return (bx, GRID - 2)


def _adjacent(a: tuple[int, int], b: tuple[int, int]) -> bool:
    return abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1


def get_edge_weight(u: int, v: int, penalty: float) -> float:
    """Soft traffic flow directionality costs based on Guidance Graph Optimization (GGO)."""
    ux, uy = u % GRID, u // GRID
    vx, vy = v % GRID, v // GRID
    dx, dy = vx - ux, vy - uy

    if dx == 1:
        act = Action.RIGHT
    elif dx == -1:
        act = Action.LEFT
    elif dy == 1:
        act = Action.DOWN
    else:
        act = Action.UP

    # 1. Perimeter directions (Counter-clockwise loop)
    if uy == 1 and act != Action.LEFT:
        return 1.0 + penalty
    if uy == 50 and act != Action.RIGHT:
        return 1.0 + penalty
    if ux == 1 and act != Action.DOWN:
        return 1.0 + penalty
    if ux == 50 and act != Action.UP:
        return 1.0 + penalty

    # 2. Vertical aisles
    if ux in {2, 8, 14, 20, 26, 32, 38, 44}:
        if act == Action.DOWN:
            return 1.0 + penalty
    elif ux in {5, 11, 17, 23, 29, 35, 41, 47}:
        if act == Action.UP:
            return 1.0 + penalty

    # 3. Horizontal aisles
    if uy in {2, 8, 14, 20, 26, 32, 38, 44}:
        if act == Action.RIGHT:
            return 1.0 + penalty
    elif uy in {5, 11, 17, 23, 29, 35, 41, 47}:
        if act == Action.LEFT:
            return 1.0 + penalty

    return 1.0


class _World:
    """Static layout geometry, connectivity list, and shortest path distance caching with GGO weights."""

    __slots__ = ("passable", "nbrs", "dist_cache", "penalty")

    def __init__(self, grid, penalty: float) -> None:
        self.penalty = penalty
        self.passable = np.zeros(GRID * GRID, dtype=bool)
        for y in range(WALK_MIN, WALK_MAX + 1):
            row = grid[y]
            for x in range(WALK_MIN, WALK_MAX + 1):
                if row[x] == CellType.EMPTY:
                    self.passable[_node(x, y)] = True

        nbrs: dict[int, tuple[tuple[Action, int, float], ...]] = {}
        passable = self.passable
        for y in range(WALK_MIN, WALK_MAX + 1):
            for x in range(WALK_MIN, WALK_MAX + 1):
                n = _node(x, y)
                if not passable[n]:
                    continue
                lst = []
                for action, dx, dy in _DIRS:
                    nx, ny = x + dx, y + dy
                    if WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX:
                        m = _node(nx, ny)
                        if passable[m]:
                            w = get_edge_weight(n, m, penalty)
                            lst.append((action, m, w))
                nbrs[n] = tuple(lst)
        self.nbrs = nbrs
        self.dist_cache: dict[tuple, np.ndarray] = {}

    def _dijkstra(self, sources: list[int]) -> np.ndarray:
        """Computes shortest path distances using Dijkstra's algorithm for weighted edges."""
        dist = np.full(GRID * GRID, INF, dtype=np.float32)
        pq: list[tuple[float, int]] = []
        for s in sources:
            dist[s] = 0.0
            heapq.heappush(pq, (0.0, s))

        nbrs = self.nbrs
        while pq:
            d, u = heapq.heappop(pq)
            if d > dist[u]:
                continue
            for _action, v, w in nbrs[u]:
                dv = d + w
                if dist[v] > dv:
                    dist[v] = dv
                    heapq.heappush(pq, (dv, v))
        return dist

    def base_field(self, entry_node: int) -> np.ndarray:
        key = ("B", entry_node)
        field = self.dist_cache.get(key)
        if field is None:
            field = self._dijkstra([entry_node])
            self.dist_cache[key] = field
        return field

    def shelf_field(self, shelf: tuple[int, int]) -> np.ndarray:
        key = ("S", shelf)
        field = self.dist_cache.get(key)
        if field is None:
            sx, sy = shelf
            sources = []
            for _action, dx, dy in _DIRS:
                nx, ny = sx + dx, sy + dy
                if WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX:
                    m = _node(nx, ny)
                    if self.passable[m]:
                        sources.append(m)
            field = self._dijkstra(sources)
            self.dist_cache[key] = field
        return field


class _Brain:
    """Centralized dynamic belief state shared among all robots."""

    __slots__ = (
        "world", "cur_tick", "pos", "base", "entry", "target", "carrying",
        "wait_streak", "moves", "locked", "occupied", "need_greedy",
        "next_claimed", "plan_final", "plan_start", "penalty",
    )

    def __init__(self, penalty: float = 0.1) -> None:
        self.world: _World | None = None
        self.cur_tick: int | None = None
        self.pos: dict[int, tuple[int, int]] = {}
        self.base: dict[int, tuple[int, int]] = {}
        self.entry: dict[int, int] = {}
        self.target: dict[int, tuple[int, int] | None] = {}
        self.carrying: dict[int, bool] = {}
        self.wait_streak: dict[int, int] = {}
        self.moves: dict[int, Action] = {}
        self.locked: frozenset[tuple[int, int]] = frozenset()
        self.occupied: frozenset[tuple[int, int]] = frozenset()
        self.need_greedy: frozenset[int] = frozenset()
        self.next_claimed: set[int] = set()
        self.plan_final: dict[int, int] = {}
        self.plan_start: dict[int, int] = {}
        self.penalty = penalty

    def reset_episode(self) -> None:
        self.cur_tick = None
        self.pos.clear()
        self.base.clear()
        self.entry.clear()
        self.target.clear()
        self.carrying.clear()
        self.wait_streak.clear()
        self.moves.clear()
        self.locked = frozenset()
        self.occupied = frozenset()
        self.need_greedy = frozenset()
        self.next_claimed = set()
        self.plan_final = {}
        self.plan_start = {}


_BRAIN = _Brain(PENALTY)


def act(observation: Observation) -> Action:
    try:
        return _act(observation)
    except Exception:
        return Action.WAIT


def _act(obs: Observation) -> Action:
    brain = _BRAIN
    if brain.world is None:
        brain.world = _World(obs.grid, brain.penalty)

    new_tick = brain.cur_tick is None or obs.tick != brain.cur_tick
    if new_tick:
        if brain.cur_tick is None or obs.tick < brain.cur_tick:
            brain.reset_episode()
        brain.cur_tick = obs.tick
        try:
            _plan(brain, obs)
        except Exception:
            brain.moves = {}

    return _action_for(brain, obs)


def _plan(brain: _Brain, obs0: Observation) -> None:
    """Run centralized path planning on the first robot's call of the tick."""
    world = brain.world
    positions = obs0.all_robot_positions

    # Sync first caller (robot 0) state
    r0 = obs0.robot_id
    brain.pos[r0] = obs0.position
    brain.base[r0] = obs0.base_position
    brain.entry[r0] = _node(*_base_entry(*obs0.base_position))
    brain.target[r0] = obs0.target_item_position
    brain.carrying[r0] = obs0.carrying_item

    for rid, xy in positions.items():
        brain.pos[rid] = (xy[0], xy[1])

    rids = sorted(positions)
    brain.occupied = frozenset(brain.pos[rid] for rid in rids)
    brain.locked = frozenset(
        t for rid in rids
        if brain.carrying.get(rid) and (t := brain.target.get(rid)) is not None
    )

    stayers: list[int] = []
    movers: list[int] = []
    need_greedy: list[int] = []
    goal_field: dict[int, np.ndarray] = {}
    for rid in rids:
        cur = brain.pos[rid]
        node = _node(*cur)
        carrying = brain.carrying.get(rid, False)
        if carrying:
            entry = brain.entry.get(rid)
            if entry is None:
                stayers.append(rid)
                continue
            field = world.base_field(entry)
            if node == entry:
                stayers.append(rid)  # will DROP
                continue
        else:
            target = brain.target.get(rid)
            if target is None:
                stayers.append(rid)
                need_greedy.append(rid)  # Just dropped off, goal revealed on its own call
                continue
            field = world.shelf_field(target)
            if float(field[node]) == 0.0:
                stayers.append(rid)  # will PICKUP
                continue
        if float(field[node]) >= INF:
            stayers.append(rid)
            continue
        goal_field[rid] = field
        movers.append(rid)

    brain.need_greedy = frozenset(need_greedy)

    cell_res: dict[tuple[int, int], int] = {}
    edge_res: dict[tuple[int, int, int], int] = {}

    # Stationary stayers block their cell over the window to avoid crashes
    for rid in stayers:
        n = _node(*brain.pos[rid])
        for t in range(WINDOW + 1):
            cell_res[(t, n)] = rid

    # Cooperative prioritized ordering (deadlock-free via priority sorting)
    def priority(rid: int):
        carrying = brain.carrying.get(rid, False)
        node = _node(*brain.pos[rid])
        entry = brain.entry.get(rid)
        remaining = float(goal_field[rid][node])
        boost = min(brain.wait_streak.get(rid, 0), WAIT_CAP)
        # Give immediate priority to clearing base entries so drop-off cells don't gridlock
        clearing_base = (not carrying and entry is not None and node == entry)
        tier = 0 if carrying else (1 if clearing_base else 2)
        return (tier, -boost, remaining, rid)

    movers.sort(key=priority)

    desired: dict[int, int] = {rid: _node(*brain.pos[rid]) for rid in rids}
    for rid in movers:
        start = _node(*brain.pos[rid])
        path = _astar(world, start, goal_field[rid], cell_res, edge_res)
        if path is None or len(path) < 2:
            desired[rid] = start
            for t in range(WINDOW + 1):
                cell_res.setdefault((t, start), rid)
            continue
        desired[rid] = path[1]
        last = len(path) - 1
        for i in range(min(last, WINDOW) + 1):
            cell_res[(i, path[i])] = rid
        for i in range(min(last, WINDOW)):
            edge_res[(i, path[i], path[i + 1])] = rid
        for t in range(last + 1, WINDOW + 1):
            cell_res[(t, path[last])] = rid

    order = stayers + movers
    final = _resolve_first_moves(brain, desired, order)

    moves: dict[int, Action] = {}
    start_nodes: dict[int, int] = {}
    for rid in rids:
        u = _node(*brain.pos[rid])
        v = final[rid]
        start_nodes[rid] = u
        moves[rid] = _delta_action(u, v)
        brain.wait_streak[rid] = 0 if v != u else brain.wait_streak.get(rid, 0) + 1
    brain.moves = moves

    brain.plan_final = dict(final)
    brain.plan_start = start_nodes
    brain.next_claimed = set(final.values())


def _astar(world, start, field, cell_res, edge_res):
    """Windowed space-time A* with GGO soft directional weights."""
    if float(field[start]) >= INF:
        return None
    if float(field[start]) == 0.0:
        return [start]

    nbrs = world.nbrs
    open_heap = [(float(field[start]), 0.0, start, 0)]
    came: dict[tuple[int, int], tuple[int, int]] = {}
    gbest: dict[tuple[int, int], float] = {(start, 0): 0.0}
    expansions = 0
    goal_state = None

    while open_heap:
        f, g, n, t = heapq.heappop(open_heap)
        if g > gbest.get((n, t), INF):
            continue
        if float(field[n]) == 0.0:
            goal_state = (n, t)
            break
        expansions += 1
        if expansions > NODE_CAP:
            break
        nt = t + 1
        within = nt <= WINDOW
        for _action, m, w in nbrs[n]:
            if within and ((nt, m) in cell_res or (t, m, n) in edge_res):
                continue
            ng = g + w  # Incremented by GGO edge weight
            key = (m, nt)
            if ng < gbest.get(key, INF):
                gbest[key] = ng
                came[key] = (n, t)
                heapq.heappush(open_heap, (ng + float(field[m]), ng, m, nt))
        # Wait action
        if not (within and (nt, n) in cell_res):
            ng = g + 1.0
            key = (n, nt)
            if ng < gbest.get(key, INF):
                gbest[key] = ng
                came[key] = (n, t)
                heapq.heappush(open_heap, (ng + float(field[n]), ng, n, nt))

    if goal_state is None:
        return None

    path = []
    state = goal_state
    while state in came:
        path.append(state[0])
        state = came[state]
    path.append(start)
    path.reverse()
    return path


def _resolve_first_moves(brain, desired, order):
    """Resolves potential head-on collisions and edge-swaps."""
    cur = {rid: _node(*brain.pos[rid]) for rid in desired}
    final = dict(desired)
    by_cur = {cur[rid]: rid for rid in desired}

    for rid in order:
        u, v = cur[rid], final[rid]
        if v == u:
            continue
        other = by_cur.get(v)
        if other is not None and other != rid and final.get(other) == u:
            final[rid] = u
            final[other] = cur[other]

    changed = True
    guard = 0
    while changed and guard < 256:
        changed = False
        guard += 1
        occ = {}
        for rid in order:
            v = final[rid]
            if v in occ:
                if final[rid] != cur[rid]:
                    final[rid] = cur[rid]
                    changed = True
            else:
                occ[v] = rid
    return final


def _delta_action(u: int, v: int) -> Action:
    if u == v:
        return Action.WAIT
    dx = (v % GRID) - (u % GRID)
    if dx == 1:
        return Action.RIGHT
    if dx == -1:
        return Action.LEFT
    return Action.DOWN if (v // GRID) - (u // GRID) == 1 else Action.UP


def _action_for(brain: _Brain, obs: Observation) -> Action:
    rid = obs.robot_id
    pos = obs.position
    target = obs.target_item_position
    carrying = obs.carrying_item

    brain.pos[rid] = pos
    brain.base[rid] = obs.base_position
    entry_xy = _base_entry(*obs.base_position)
    brain.entry[rid] = _node(*entry_xy)
    brain.target[rid] = target
    brain.carrying[rid] = carrying

    if carrying:
        if pos == entry_xy:
            brain.carrying[rid] = False
            brain.target[rid] = None
            return Action.DROP
    else:
        if _adjacent(pos, target) and target not in brain.locked:
            brain.carrying[rid] = True
            return Action.PICKUP

    move = brain.moves.get(rid)
    if move is None or (move == Action.WAIT and rid in brain.need_greedy):
        move = _coordinated_step(brain, obs)
    return move


def _coordinated_step(brain: _Brain, obs: Observation) -> Action:
    """Coordinated greedy step for unrouted robots."""
    world = brain.world
    rid = obs.robot_id
    x, y = obs.position
    cnode = _node(x, y)

    if obs.carrying_item:
        field = world.base_field(_node(*_base_entry(*obs.base_position)))
    else:
        target = obs.target_item_position
        if target is None:
            return Action.WAIT
        field = world.shelf_field(target)

    claimed = brain.next_claimed
    plan_final = brain.plan_final
    plan_start = brain.plan_start

    best_action = Action.WAIT
    best_node = cnode
    best_key = (float(field[cnode]), y, x)

    for action, dx, dy in _DIRS:
        nx, ny = x + dx, y + dy
        if not (WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX):
            continue
        m = _node(nx, ny)
        if not world.passable[m] or (m != cnode and m in claimed):
            continue

        swap = False
        for orid, fnode in plan_final.items():
            if orid != rid and fnode == cnode and plan_start.get(orid) == m:
                swap = True
                break
        if swap:
            continue

        w = get_edge_weight(cnode, m, brain.world.penalty)
        key = (float(field[m]) + (w - 1.0), ny, nx)
        if key < best_key:
            best_key = key
            best_action = action
            best_node = m

    if best_node != cnode:
        claimed.discard(cnode)
        claimed.add(best_node)
        plan_final[rid] = best_node
        plan_start[rid] = cnode

    return best_action
