# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 09
# job:        b867727fbfbe  (https://refugio-hackathon-nine.vercel.app/jobs/b867727fbfbe)
# deliveries: 897    points: 0    runtime: 22.93s
# submitted:  2026-06-27 12:20:15.231 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/b867727fbfbe    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0897__equipo-09__b867727fbfbe.py --count 20
# ===========================================================================

"""REFUGIO — best policy: flow + congestion + endgame + short stayer res + detour (924 local)."""

from __future__ import annotations

import heapq
from collections import deque

import numpy as np

from warehouse_api import Action, CellType, Observation

GRID = 52
WALK_MIN = 1
WALK_MAX = 50
INF = 1 << 29

WINDOW = 24
NODE_CAP = 2500
WAIT_CAP = 30
FLOW_PENALTY = 0.2
CONGEST_W = 0.1
HORIZON = 300

_DIRS = (
    (Action.UP, 0, -1),
    (Action.DOWN, 0, 1),
    (Action.LEFT, -1, 0),
    (Action.RIGHT, 1, 0),
)


def _node(x: int, y: int) -> int:
    return y * GRID + x


def _base_entry_cells() -> set[tuple[int, int]]:
    entries: set[tuple[int, int]] = set()
    for x in range(3, 50, 2):
        entries.add((x, 1))
    for x in range(2, 49, 2):
        entries.add((x, 50))
    for y in range(2, 49, 2):
        entries.add((1, y))
    for y in range(3, 50, 2):
        entries.add((50, y))
    return entries


def create_layout() -> dict[str, object]:
    block_w, block_h, aisle_w, aisle_h, margin = 2, 3, 1, 1, 2
    lo, hi = 1 + margin, 50 - margin
    period_x, period_y = block_w + aisle_w, block_h + aisle_h

    cells: list[tuple[int, int]] = []
    x = lo
    while x <= hi:
        y = lo
        while y <= hi:
            for cx in range(x, min(x + block_w, hi + 1)):
                for cy in range(y, min(y + block_h, hi + 1)):
                    cells.append((cx, cy))
            y += period_y
        x += period_x

    entries = _base_entry_cells()
    cells = [c for c in cells if c not in entries]

    n = len(cells)
    extra = n - 960
    if extra > 0:
        removed: set[int] = set()
        for k in range(extra):
            idx = (k * n) // extra + n // (2 * extra)
            while idx in removed:
                idx = (idx + 1) % n
            removed.add(idx)
        cells = [c for i, c in enumerate(cells) if i not in removed]

    shelves: list[list[int]] = [[cx, cy] for (cx, cy) in cells]
    return {"schema_version": 1, "shelves": shelves}


def _base_entry(bx: int, by: int) -> tuple[int, int]:
    if bx == 0:
        return (1, by)
    if bx == GRID - 1:
        return (GRID - 2, by)
    if by == 0:
        return (bx, 1)
    return (bx, GRID - 2)


def _adjacent(a: tuple[int, int], b: tuple[int, int]) -> bool:
    return abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1


class _World:
    __slots__ = ("passable", "nbrs", "dist_cache", "flow_costs")

    def __init__(self, grid) -> None:
        self.passable = np.zeros(GRID * GRID, dtype=bool)
        for y in range(WALK_MIN, WALK_MAX + 1):
            row = grid[y]
            for x in range(WALK_MIN, WALK_MAX + 1):
                if row[x] == CellType.EMPTY:
                    self.passable[_node(x, y)] = True

        nbrs: dict[int, tuple[tuple[Action, int], ...]] = {}
        flow_costs: dict[tuple[int, int], float] = {}
        passable = self.passable
        for y in range(WALK_MIN, WALK_MAX + 1):
            for x in range(WALK_MIN, WALK_MAX + 1):
                u = _node(x, y)
                if not passable[u]:
                    continue
                lst = []
                for action, dx, dy in _DIRS:
                    nx, ny = x + dx, y + dy
                    if WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX:
                        v = _node(nx, ny)
                        if passable[v]:
                            lst.append((action, v))
                            penalty = 0.0
                            if x == nx and x % 3 == 2:
                                if (x // 3) % 2 == 0 and ny > y:
                                    penalty = FLOW_PENALTY
                                elif (x // 3) % 2 == 1 and ny < y:
                                    penalty = FLOW_PENALTY
                            elif y == ny and y % 4 == 2:
                                if (y // 4) % 2 == 0 and nx > x:
                                    penalty = FLOW_PENALTY
                                elif (y // 4) % 2 == 1 and nx < x:
                                    penalty = FLOW_PENALTY
                            elif y == 2 and nx > x:
                                penalty = FLOW_PENALTY
                            elif y == 49 and nx < x:
                                penalty = FLOW_PENALTY
                            elif x == 2 and ny > y:
                                penalty = FLOW_PENALTY
                            elif x == 49 and ny < y:
                                penalty = FLOW_PENALTY
                            if penalty > 0:
                                flow_costs[(u, v)] = penalty
                nbrs[u] = tuple(lst)
        self.nbrs = nbrs
        self.flow_costs = flow_costs
        self.dist_cache: dict[tuple, np.ndarray] = {}

    def _bfs(self, sources: list[int]) -> np.ndarray:
        dist = np.full(GRID * GRID, INF, dtype=np.int32)
        dq: deque[int] = deque()
        for s in sources:
            if dist[s] != 0:
                dist[s] = 0
                dq.append(s)
        nbrs = self.nbrs
        while dq:
            u = dq.popleft()
            du = dist[u] + 1
            for _action, v in nbrs[u]:
                if dist[v] > du:
                    dist[v] = du
                    dq.append(v)
        return dist

    def base_field(self, entry_node: int) -> np.ndarray:
        key = ("B", entry_node)
        field = self.dist_cache.get(key)
        if field is None:
            field = self._bfs([entry_node])
            self.dist_cache[key] = field
        return field

    def shelf_field(self, shelf: tuple[int, int]) -> np.ndarray:
        key = ("S", shelf)
        field = self.dist_cache.get(key)
        if field is None:
            sx, sy = shelf
            sources = []
            for _action, dx, dy in _DIRS:
                nx, ny = sx + dx, sy + dy
                if WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX:
                    m = _node(nx, ny)
                    if self.passable[m]:
                        sources.append(m)
            field = self._bfs(sources)
            self.dist_cache[key] = field
        return field


class _Brain:
    __slots__ = (
        "world", "cur_tick", "pos", "base", "entry", "target", "carrying",
        "wait_streak", "moves", "locked", "occupied", "need_greedy",
        "next_claimed", "plan_final", "plan_start", "congest",
    )

    def __init__(self) -> None:
        self.world: _World | None = None
        self.cur_tick: int | None = None
        self.pos: dict[int, tuple[int, int]] = {}
        self.base: dict[int, tuple[int, int]] = {}
        self.entry: dict[int, int] = {}
        self.target: dict[int, tuple[int, int] | None] = {}
        self.carrying: dict[int, bool] = {}
        self.wait_streak: dict[int, int] = {}
        self.moves: dict[int, Action] = {}
        self.locked: frozenset[tuple[int, int]] = frozenset()
        self.occupied: frozenset[tuple[int, int]] = frozenset()
        self.need_greedy: frozenset[int] = frozenset()
        self.next_claimed: set[int] = set()
        self.plan_final: dict[int, int] = {}
        self.plan_start: dict[int, int] = {}
        self.congest = np.zeros(GRID * GRID, dtype=np.float32)

    def reset_episode(self) -> None:
        self.cur_tick = None
        self.pos.clear()
        self.base.clear()
        self.entry.clear()
        self.target.clear()
        self.carrying.clear()
        self.wait_streak.clear()
        self.moves.clear()
        self.locked = frozenset()
        self.occupied = frozenset()
        self.need_greedy = frozenset()
        self.next_claimed = set()
        self.plan_final = {}
        self.plan_start = {}
        self.congest = np.zeros(GRID * GRID, dtype=np.float32)


_BRAIN = _Brain()


def act(observation: Observation) -> Action:
    try:
        return _act(observation)
    except Exception:
        return Action.WAIT


def _act(obs: Observation) -> Action:
    brain = _BRAIN
    if brain.world is None:
        brain.world = _World(obs.grid)

    new_tick = brain.cur_tick is None or obs.tick != brain.cur_tick
    if new_tick:
        if brain.cur_tick is None or obs.tick < brain.cur_tick:
            brain.reset_episode()
        brain.cur_tick = obs.tick
        try:
            _plan(brain, obs)
        except Exception:
            brain.moves = {}

    return _action_for(brain, obs)


def _plan(brain: _Brain, obs0: Observation) -> None:
    world = brain.world
    positions = obs0.all_robot_positions

    r0 = obs0.robot_id
    brain.pos[r0] = obs0.position
    brain.base[r0] = obs0.base_position
    brain.entry[r0] = _node(*_base_entry(*obs0.base_position))
    brain.target[r0] = obs0.target_item_position
    brain.carrying[r0] = obs0.carrying_item

    for rid, xy in positions.items():
        brain.pos[rid] = (xy[0], xy[1])

    rids = sorted(positions)
    brain.occupied = frozenset(brain.pos[rid] for rid in rids)

    congest = brain.congest
    congest.fill(0)
    for rid in rids:
        rx, ry = brain.pos[rid]
        for ddx in (-1, 0, 1):
            for ddy in (-1, 0, 1):
                cx, cy = rx + ddx, ry + ddy
                if WALK_MIN <= cx <= WALK_MAX and WALK_MIN <= cy <= WALK_MAX:
                    congest[_node(cx, cy)] += 1.0

    brain.locked = frozenset(
        t for rid in rids
        if brain.carrying.get(rid) and (t := brain.target.get(rid)) is not None
    )

    stayers: list[int] = []
    movers: list[int] = []
    need_greedy: list[int] = []
    short_stayers: set[int] = set()
    goal_field: dict[int, np.ndarray] = {}
    for rid in rids:
        cur = brain.pos[rid]
        node = _node(*cur)
        carrying = brain.carrying.get(rid, False)
        if carrying:
            entry = brain.entry.get(rid)
            if entry is None:
                stayers.append(rid)
                continue
            field = world.base_field(entry)
            if node == entry:
                stayers.append(rid)
                short_stayers.add(rid)
                continue
        else:
            target = brain.target.get(rid)
            if target is None:
                stayers.append(rid)
                need_greedy.append(rid)
                short_stayers.add(rid)
                continue
            field = world.shelf_field(target)
            if int(field[node]) == 0:
                stayers.append(rid)
                short_stayers.add(rid)
                continue
        if int(field[node]) >= INF:
            stayers.append(rid)
            continue
        goal_field[rid] = field
        movers.append(rid)

    brain.need_greedy = frozenset(need_greedy)

    cell_res: dict[tuple[int, int], int] = {}
    edge_res: dict[tuple[int, int, int], int] = {}

    for rid in stayers:
        n = _node(*brain.pos[rid])
        horizon = 1 if rid in short_stayers else WINDOW + 1
        for t in range(horizon):
            cell_res[(t, n)] = rid

    remaining_time = HORIZON - obs0.tick

    def priority(rid: int):
        carrying = brain.carrying.get(rid, False)
        pos = brain.pos[rid]
        node = _node(*pos)
        remaining = int(goal_field[rid][node])
        boost = min(brain.wait_streak.get(rid, 0), WAIT_CAP)
        if carrying:
            eta = remaining + 1
        else:
            tgt = brain.target.get(rid)
            base = brain.base.get(rid)
            if tgt is not None and base is not None:
                ex, ey = _base_entry(*base)
                back = abs(tgt[0] - ex) + abs(tgt[1] - ey) - 1
                eta = remaining + 2 + (back if back > 0 else 0)
            else:
                eta = remaining + 2
        can_deliver = 0 if eta <= remaining_time else 1
        dist_from_center = abs(pos[0] - 25) + abs(pos[1] - 25)
        return (can_deliver, 0 if carrying else 1, -boost, remaining, dist_from_center, rid)

    movers.sort(key=priority)

    desired: dict[int, int] = {rid: _node(*brain.pos[rid]) for rid in rids}
    for rid in movers:
        start = _node(*brain.pos[rid])
        path = _astar(world, start, goal_field[rid], cell_res, edge_res, congest)
        if path is None or len(path) < 2:
            desired[rid] = start
            for t in range(WINDOW + 1):
                cell_res.setdefault((t, start), rid)
            continue
        desired[rid] = path[1]
        last = len(path) - 1
        for i in range(min(last, WINDOW) + 1):
            cell_res[(i, path[i])] = rid
        for i in range(min(last, WINDOW)):
            edge_res[(i, path[i], path[i + 1])] = rid
        for t in range(last + 1, WINDOW + 1):
            cell_res[(t, path[last])] = rid

    order = stayers + movers
    final = _resolve_first_moves(brain, desired, order)

    moves: dict[int, Action] = {}
    start_nodes: dict[int, int] = {}
    for rid in rids:
        u = _node(*brain.pos[rid])
        v = final[rid]
        start_nodes[rid] = u
        moves[rid] = _delta_action(u, v)
        brain.wait_streak[rid] = 0 if v != u else brain.wait_streak.get(rid, 0) + 1
    brain.moves = moves

    brain.plan_final = dict(final)
    brain.plan_start = start_nodes
    brain.next_claimed = set(final.values())


def _astar(world, start, field, cell_res, edge_res, congest):
    if int(field[start]) >= INF:
        return None
    if int(field[start]) == 0:
        return [start]

    nbrs = world.nbrs
    flow_costs = world.flow_costs
    open_heap = [(float(field[start]), 0.0, start, 0)]
    came: dict[tuple[int, int], tuple[int, int]] = {}
    gbest: dict[tuple[int, int], float] = {(start, 0): 0.0}
    expansions = 0
    goal_state = None
    while open_heap:
        f, g, n, t = heapq.heappop(open_heap)
        if g > gbest.get((n, t), INF):
            continue
        if int(field[n]) == 0:
            goal_state = (n, t)
            break
        expansions += 1
        if expansions > NODE_CAP:
            break
        nt = t + 1
        within = nt <= WINDOW
        for action, m in nbrs[n]:
            if within and ((nt, m) in cell_res or (t, m, n) in edge_res):
                continue
            ng = g + 1.0 + flow_costs.get((n, m), 0.0) + CONGEST_W * float(congest[m])
            key = (m, nt)
            if ng < gbest.get(key, INF):
                gbest[key] = ng
                came[key] = (n, t)
                heapq.heappush(open_heap, (ng + float(field[m]), ng, m, nt))
        if not (within and (nt, n) in cell_res):
            ng = g + 1.01 + CONGEST_W * float(congest[n])
            key = (n, nt)
            if ng < gbest.get(key, INF):
                gbest[key] = ng
                came[key] = (n, t)
                heapq.heappush(open_heap, (ng + float(field[n]), ng, n, nt))

    if goal_state is None:
        return None
    path = []
    state = goal_state
    while state in came:
        path.append(state[0])
        state = came[state]
    path.append(start)
    path.reverse()
    return path


def _resolve_first_moves(brain, desired, order):
    cur = {rid: _node(*brain.pos[rid]) for rid in desired}
    final = dict(desired)
    by_cur = {cur[rid]: rid for rid in desired}

    for rid in order:
        u, v = cur[rid], final[rid]
        if v == u:
            continue
        other = by_cur.get(v)
        if other is not None and other != rid and final.get(other) == u:
            final[rid] = u
            final[other] = cur[other]

    occ: dict[int, int] = {}
    blocked: set[int] = set()
    for rid in order:
        v = final[rid]
        if v in occ:
            final[rid] = cur[rid]
            blocked.add(rid)
        else:
            occ[v] = rid
            if v == cur[rid]:
                blocked.add(rid)

    world = brain.world
    for rid in order:
        if rid not in blocked or final[rid] != cur[rid]:
            continue
        if desired[rid] == cur[rid]:
            continue
        u = cur[rid]
        for _, v in world.nbrs[u]:
            if v not in occ:
                swap = False
                other_rid = by_cur.get(v)
                if other_rid is not None and final[other_rid] == u:
                    swap = True
                if not swap:
                    final[rid] = v
                    occ[v] = rid
                    break
    return final


def _delta_action(u: int, v: int) -> Action:
    if u == v:
        return Action.WAIT
    dx = (v % GRID) - (u % GRID)
    if dx == 1:
        return Action.RIGHT
    if dx == -1:
        return Action.LEFT
    return Action.DOWN if (v // GRID) - (u // GRID) == 1 else Action.UP


def _action_for(brain: _Brain, obs: Observation) -> Action:
    rid = obs.robot_id
    pos = obs.position
    target = obs.target_item_position
    carrying = obs.carrying_item

    brain.pos[rid] = pos
    brain.base[rid] = obs.base_position
    entry_xy = _base_entry(*obs.base_position)
    brain.entry[rid] = _node(*entry_xy)
    brain.target[rid] = target
    brain.carrying[rid] = carrying

    if carrying:
        if pos == entry_xy:
            brain.carrying[rid] = False
            brain.target[rid] = None
            return Action.DROP
    else:
        if _adjacent(pos, target) and target not in brain.locked:
            brain.carrying[rid] = True
            return Action.PICKUP

    move = brain.moves.get(rid)
    if move is None or (move == Action.WAIT and rid in brain.need_greedy):
        move = _coordinated_step(brain, obs)
    return move


def _coordinated_step(brain: _Brain, obs: Observation) -> Action:
    world = brain.world
    rid = obs.robot_id
    x, y = obs.position
    cnode = _node(x, y)
    if obs.carrying_item:
        field = world.base_field(_node(*_base_entry(*obs.base_position)))
    else:
        target = obs.target_item_position
        if target is None:
            return Action.WAIT
        field = world.shelf_field(target)

    claimed = brain.next_claimed
    plan_final = brain.plan_final
    plan_start = brain.plan_start
    congest = brain.congest

    best_action = Action.WAIT
    best_node = cnode
    best_key = (int(field[cnode]) + CONGEST_W * float(congest[cnode]), y, x)
    for action, dx, dy in _DIRS:
        nx, ny = x + dx, y + dy
        if not (WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX):
            continue
        m = _node(nx, ny)
        if not world.passable[m]:
            continue
        if m != cnode and m in claimed:
            continue
        swap = False
        for orid, fnode in plan_final.items():
            if orid != rid and fnode == cnode and plan_start.get(orid) == m:
                swap = True
                break
        if swap:
            continue
        key = (int(field[m]) + CONGEST_W * float(congest[m]), ny, nx)
        if key < best_key:
            best_key = key
            best_action = action
            best_node = m

    if best_node != cnode:
        claimed.discard(cnode)
        claimed.add(best_node)
        plan_final[rid] = best_node
        plan_start[rid] = cnode
    return best_action
