# === SCRAPED RIVAL SOLUTION (do not edit; regenerated by tools/scrape.py) ===
# team:       Equipo 08
# job:        64584e8c4c8d  (https://refugio-hackathon-nine.vercel.app/jobs/64584e8c4c8d)
# deliveries: 904    points: 0    runtime: 16.86s
# submitted:  2026-06-27 12:57:40.056 UTC
# code page:  https://refugio-hackathon-nine.vercel.app/code/64584e8c4c8d    original file label: policy.py
# To evaluate in our bench: python tools/benchmark.py scraped/solutions/0904__equipo-08__64584e8c4c8d.py --count 20
# ===========================================================================

"""v57: v56 + WINDOW=35.

Tests if longer planning horizon works with our remaining-distance
priority and 2x3 layout (like Equipo 03's W=35 approach).
"""

from __future__ import annotations

import heapq
from collections import deque

from warehouse_api import Action, CellType, Observation, Position

GRID = 52
WALK_MIN = 1
WALK_MAX = 50
INF = 1 << 29
WINDOW = 35
NODE_CAP = 2500
WAIT_CAP = 30
FLOW_PENALTY = 0.1
BLOCK_W, BLOCK_H, MARGIN_LAYOUT = 2, 3, 2
LO_LAYOUT = 1 + MARGIN_LAYOUT
PERIOD_X = BLOCK_W + 1
PERIOD_Y = BLOCK_H + 1

_DIRS = (
    (Action.UP, 0, -1),
    (Action.DOWN, 0, 1),
    (Action.LEFT, -1, 0),
    (Action.RIGHT, 1, 0),
)
_DIR_DELTAS = [(1, 0), (-1, 0), (0, 1), (0, -1)]


def _node(x, y):
    return y * GRID + x


def _base_entry_cells():
    entries = set()
    for x in range(3, 50, 2):
        entries.add((x, 1))
    for x in range(2, 49, 2):
        entries.add((x, 50))
    for y in range(2, 49, 2):
        entries.add((1, y))
    for y in range(3, 50, 2):
        entries.add((50, y))
    return entries


def create_layout():
    block_w, block_h, aisle_w, aisle_h, margin = 2, 3, 1, 1, 2
    lo, hi = 1 + margin, 50 - margin
    period_x, period_y = block_w + aisle_w, block_h + aisle_h

    cells = []
    x = lo
    while x <= hi:
        y = lo
        while y <= hi:
            for cx in range(x, min(x + block_w, hi + 1)):
                for cy in range(y, min(y + block_h, hi + 1)):
                    cells.append((cx, cy))
            y += period_y
        x += period_x

    entries = _base_entry_cells()
    cells = [c for c in cells if c not in entries]

    n = len(cells)
    extra = n - 960
    if extra > 0:
        removed = set()
        for k in range(extra):
            idx = (k * n) // extra + n // (2 * extra)
            while idx in removed:
                idx = (idx + 1) % n
            removed.add(idx)
        cells = [c for i, c in enumerate(cells) if i not in removed]

    shelves = [[cx, cy] for (cx, cy) in cells]
    return {"schema_version": 1, "shelves": shelves}


def _base_entry(bx, by):
    # Corner bases need special handling — their naive entry lands outside walkable area
    if bx == 0 and by == 0:
        return (1, 1)
    if bx == 0 and by == GRID - 1:
        return (1, GRID - 2)
    if bx == GRID - 1 and by == 0:
        return (GRID - 2, 1)
    if bx == GRID - 1 and by == GRID - 1:
        return (GRID - 2, GRID - 2)
    if bx == 0:
        return (1, by)
    if bx == GRID - 1:
        return (GRID - 2, by)
    if by == 0:
        return (bx, 1)
    return (bx, GRID - 2)


def _adjacent(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1


def _flow(x, y, nx, ny):
    """Period-aware soft one-way bias. Returns penalty for moving x,y -> nx,ny."""
    # Vertical aisle: the column right after each block
    if x == nx and (x - LO_LAYOUT) % PERIOD_X == BLOCK_W:
        col_idx = (x - LO_LAYOUT) // PERIOD_X
        if col_idx % 2 == 0 and ny > y:
            return FLOW_PENALTY
        if col_idx % 2 == 1 and ny < y:
            return FLOW_PENALTY
    # Horizontal aisle: the row right after each block
    if y == ny and (y - LO_LAYOUT) % PERIOD_Y == BLOCK_H:
        row_idx = (y - LO_LAYOUT) // PERIOD_Y
        if row_idx % 2 == 0 and nx > x:
            return FLOW_PENALTY
        if row_idx % 2 == 1 and nx < x:
            return FLOW_PENALTY
    # Perimeter highways
    if y == 2 and nx > x:
        return FLOW_PENALTY
    if y == 49 and nx < x:
        return FLOW_PENALTY
    if x == 2 and ny > y:
        return FLOW_PENALTY
    if x == 49 and ny < y:
        return FLOW_PENALTY
    return 0.0


class _World:
    def __init__(self, grid):
        self.passable = {}
        self.nbrs = {}
        self.dist_cache = {}
        self.flow_costs = {}

        for y in range(WALK_MIN, WALK_MAX + 1):
            for x in range(WALK_MIN, WALK_MAX + 1):
                n = _node(x, y)
                if grid[y][x] == CellType.EMPTY:
                    self.passable[n] = True

        for y in range(WALK_MIN, WALK_MAX + 1):
            for x in range(WALK_MIN, WALK_MAX + 1):
                n = _node(x, y)
                if not self.passable.get(n):
                    continue
                lst = []
                for action, dx, dy in _DIRS:
                    nx, ny = x + dx, y + dy
                    if WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX:
                        m = _node(nx, ny)
                        if self.passable.get(m):
                            lst.append((action, m))
                            if FLOW_PENALTY > 0:
                                p = _flow(x, y, nx, ny)
                                if p > 0:
                                    self.flow_costs[(n, m)] = p
                self.nbrs[n] = tuple(lst)

    def _bfs(self, sources):
        dist = {s: INF for s in self.passable}
        q = deque()
        for s in sources:
            if dist.get(s, INF) != 0:
                dist[s] = 0
                q.append(s)
        while q:
            u = q.popleft()
            du = dist[u] + 1
            for _action, v in self.nbrs[u]:
                if dist.get(v, INF) > du:
                    dist[v] = du
                    q.append(v)
        return dist

    def base_field(self, entry_node):
        key = ("B", entry_node)
        f = self.dist_cache.get(key)
        if f is None:
            f = self._bfs([entry_node])
            self.dist_cache[key] = f
        return f

    def shelf_field(self, shelf):
        key = ("S", shelf)
        f = self.dist_cache.get(key)
        if f is None:
            sx, sy = shelf
            sources = []
            for _action, dx, dy in _DIRS:
                nx, ny = sx + dx, sy + dy
                if WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX:
                    m = _node(nx, ny)
                    if self.passable.get(m):
                        sources.append(m)
            f = self._bfs(sources)
            self.dist_cache[key] = f
        return f


class _Brain:
    def __init__(self):
        self.world = None
        self.cur_tick = None
        self.pos = {}
        self.base = {}
        self.entry = {}
        self.target = {}
        self.carrying = {}
        self.wait_streak = {}
        self.moves = {}
        self.locked = frozenset()
        self.occupied = frozenset()
        self.need_greedy = frozenset()
        self.next_claimed = set()
        self.plan_final = {}
        self.plan_start = {}

    def reset_episode(self):
        self.cur_tick = None
        self.pos.clear()
        self.base.clear()
        self.entry.clear()
        self.target.clear()
        self.carrying.clear()
        self.wait_streak.clear()
        self.moves.clear()
        self.locked = frozenset()
        self.occupied = frozenset()
        self.need_greedy = frozenset()
        self.next_claimed = set()
        self.plan_final = {}
        self.plan_start = {}


_BRAIN = _Brain()


def act(observation):
    try:
        return _act(observation)
    except Exception:
        return Action.WAIT


def _act(obs):
    brain = _BRAIN
    if brain.world is None:
        brain.world = _World(obs.grid)

    new_tick = brain.cur_tick is None or obs.tick != brain.cur_tick
    if new_tick:
        if brain.cur_tick is None or obs.tick < brain.cur_tick:
            brain.reset_episode()
        brain.cur_tick = obs.tick
        try:
            _plan(brain, obs)
        except Exception:
            brain.moves = {}

    return _action_for(brain, obs)


def _plan(brain, obs0):
    world = brain.world
    positions = obs0.all_robot_positions

    r0 = obs0.robot_id
    brain.pos[r0] = obs0.position
    brain.base[r0] = obs0.base_position
    brain.entry[r0] = _node(*_base_entry(*obs0.base_position))
    brain.target[r0] = obs0.target_item_position
    brain.carrying[r0] = obs0.carrying_item

    for rid, xy in positions.items():
        brain.pos[rid] = (xy[0], xy[1])

    rids = sorted(positions)
    brain.occupied = frozenset(brain.pos[rid] for rid in rids)
    brain.locked = frozenset(
        t for rid in rids
        if brain.carrying.get(rid) and (t := brain.target.get(rid)) is not None
    )

    stayers = []
    movers = []
    need_greedy = []
    goal_field = {}
    for rid in rids:
        cur = brain.pos[rid]
        node = _node(*cur)
        carrying = brain.carrying.get(rid, False)
        if carrying:
            entry = brain.entry.get(rid)
            if entry is None:
                stayers.append(rid)
                continue
            field = world.base_field(entry)
            if node == entry:
                stayers.append(rid)
                continue
        else:
            target = brain.target.get(rid)
            if target is None:
                stayers.append(rid)
                need_greedy.append(rid)
                continue
            field = world.shelf_field(target)
            if field.get(node, INF) == 0:
                stayers.append(rid)
                continue
        if field.get(node, INF) >= INF:
            stayers.append(rid)
            continue
        goal_field[rid] = field
        movers.append(rid)

    brain.need_greedy = frozenset(need_greedy)

    cell_res = {}
    edge_res = {}

    for rid in stayers:
        n = _node(*brain.pos[rid])
        for t in range(WINDOW + 1):
            cell_res[(t, n)] = rid

    def priority(rid):
        pos = brain.pos[rid]
        node = _node(*pos)
        remaining = int(goal_field[rid][node])
        boost = min(brain.wait_streak.get(rid, 0), WAIT_CAP)
        dc = abs(pos[0] - 25) + abs(pos[1] - 25)
        return (remaining, -boost, dc, rid)

    movers.sort(key=priority)

    desired = {rid: _node(*brain.pos[rid]) for rid in rids}
    for rid in movers:
        start = _node(*brain.pos[rid])
        path = _astar(world, start, goal_field[rid], cell_res, edge_res)
        if path is None or len(path) < 2:
            desired[rid] = start
            for t in range(WINDOW + 1):
                cell_res.setdefault((t, start), rid)
            continue
        desired[rid] = path[1]
        last = len(path) - 1
        for i in range(min(last, WINDOW) + 1):
            cell_res[(i, path[i])] = rid
        for i in range(min(last, WINDOW)):
            edge_res[(i, path[i], path[i + 1])] = rid
        for t in range(last + 1, WINDOW + 1):
            cell_res[(t, path[last])] = rid

    order = stayers + movers
    final = _resolve_first_moves(brain, desired, order)

    moves = {}
    start_nodes = {}
    for rid in rids:
        u = _node(*brain.pos[rid])
        v = final[rid]
        start_nodes[rid] = u
        moves[rid] = _delta_action(u, v)
        brain.wait_streak[rid] = 0 if v != u else brain.wait_streak.get(rid, 0) + 1
    brain.moves = moves
    brain.plan_final = dict(final)
    brain.plan_start = start_nodes
    brain.next_claimed = set(final.values())


def _astar(world, start, field, cell_res, edge_res):
    if field.get(start, INF) >= INF:
        return None
    if field.get(start, INF) == 0:
        return [start]

    nbrs = world.nbrs
    flow_costs = world.flow_costs
    open_heap = [(float(field[start]), 0.0, start, 0)]
    came = {}
    gbest = {(start, 0): 0.0}
    expansions = 0
    goal_state = None

    while open_heap:
        f, g, n, t = heapq.heappop(open_heap)
        if g > gbest.get((n, t), INF):
            continue
        if field.get(n, INF) == 0:
            goal_state = (n, t)
            break
        expansions += 1
        if expansions > NODE_CAP:
            break
        nt = t + 1
        within = nt <= WINDOW
        for _action, m in nbrs[n]:
            if within and ((nt, m) in cell_res or (t, m, n) in edge_res):
                continue
            ng = g + 1.0 + flow_costs.get((n, m), 0.0)
            key = (m, nt)
            if ng < gbest.get(key, INF):
                gbest[key] = ng
                came[key] = (n, t)
                heapq.heappush(open_heap, (ng + float(field[m]), ng, m, nt))
        if not (within and (nt, n) in cell_res):
            ng = g + 1.01  # wait costs slightly more than move
            key = (n, nt)
            if ng < gbest.get(key, INF):
                gbest[key] = ng
                came[key] = (n, t)
                heapq.heappush(open_heap, (ng + float(field[n]), ng, n, nt))

    if goal_state is None:
        return None
    path = []
    state = goal_state
    while state in came:
        path.append(state[0])
        state = came[state]
    path.append(start)
    path.reverse()
    return path


def _resolve_first_moves(brain, desired, order):
    cur = {rid: _node(*brain.pos[rid]) for rid in desired}
    final = dict(desired)
    by_cur = {cur[rid]: rid for rid in desired}

    # Detect and resolve swaps
    for rid in order:
        u, v = cur[rid], final[rid]
        if v == u:
            continue
        other = by_cur.get(v)
        if other is not None and other != rid and final.get(other) == u:
            final[rid] = u
            final[other] = cur[other]

    # Resolve collisions: first robot in order wins
    occ = {}
    blocked = set()
    for rid in order:
        v = final[rid]
        if v in occ:
            final[rid] = cur[rid]
            blocked.add(rid)
        else:
            occ[v] = rid
            if v == cur[rid]:
                blocked.add(rid)

    # Fallback: find alternative cell for blocked robots
    world = brain.world
    for rid in order:
        if rid not in blocked or final[rid] != cur[rid]:
            continue
        if desired[rid] == cur[rid]:
            continue
        u = cur[rid]
        for _action, v in world.nbrs[u]:
            if v not in occ:
                swap = False
                other_rid = by_cur.get(v)
                if other_rid is not None and final.get(other_rid) == u:
                    swap = True
                if not swap:
                    final[rid] = v
                    occ[v] = rid
                    break
    return final


def _delta_action(u, v):
    if u == v:
        return Action.WAIT
    dx = (v % GRID) - (u % GRID)
    if dx == 1:
        return Action.RIGHT
    if dx == -1:
        return Action.LEFT
    return Action.DOWN if (v // GRID) - (u // GRID) == 1 else Action.UP


def _action_for(brain, obs):
    rid = obs.robot_id
    pos = obs.position
    target = obs.target_item_position
    carrying = obs.carrying_item

    brain.pos[rid] = pos
    brain.base[rid] = obs.base_position
    entry_xy = _base_entry(*obs.base_position)
    brain.entry[rid] = _node(*entry_xy)
    brain.target[rid] = target
    brain.carrying[rid] = carrying

    if carrying:
        if pos == entry_xy:
            brain.carrying[rid] = False
            brain.target[rid] = None
            return Action.DROP
    else:
        if _adjacent(pos, target) and target not in brain.locked:
            brain.carrying[rid] = True
            return Action.PICKUP

    move = brain.moves.get(rid)
    if move is None or (move == Action.WAIT and rid in brain.need_greedy):
        move = _coordinated_step(brain, obs)
    return move


def _coordinated_step(brain, obs):
    """Plan-aware greedy step that respects coordinated robot moves."""
    world = brain.world
    rid = obs.robot_id
    x, y = obs.position
    cnode = _node(x, y)
    if obs.carrying_item:
        field = world.base_field(_node(*_base_entry(*obs.base_position)))
    else:
        target = obs.target_item_position
        if target is None:
            return Action.WAIT
        field = world.shelf_field(target)

    claimed = brain.next_claimed
    plan_final = brain.plan_final
    plan_start = brain.plan_start

    best_action = Action.WAIT
    best_node = cnode
    best_key = (int(field.get(cnode, INF)), y, x)
    for action, dx, dy in _DIRS:
        nx, ny = x + dx, y + dy
        if not (WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX):
            continue
        m = _node(nx, ny)
        if not world.passable.get(m):
            continue
        if m != cnode and m in claimed:
            continue
        swap = False
        for orid, fnode in plan_final.items():
            if orid != rid and fnode == cnode and plan_start.get(orid) == m:
                swap = True
                break
        if swap:
            continue
        key = (int(field.get(m, INF)), ny, nx)
        if key < best_key:
            best_key = key
            best_action = action
            best_node = m

    if best_node != cnode:
        claimed.discard(cnode)
        claimed.add(best_node)
        plan_final[rid] = best_node
        plan_start[rid] = cnode
    return best_action


def _greedy_step(brain, obs):
    world = brain.world
    x, y = obs.position
    if obs.carrying_item:
        field = world.base_field(_node(*_base_entry(*obs.base_position)))
    else:
        target = obs.target_item_position
        if target is None:
            return Action.WAIT
        field = world.shelf_field(target)

    occupied = brain.occupied
    best_action = Action.WAIT
    best_key = (int(field.get(_node(x, y), INF)), y, x)
    for action, dx, dy in _DIRS:
        nx, ny = x + dx, y + dy
        if not (WALK_MIN <= nx <= WALK_MAX and WALK_MIN <= ny <= WALK_MAX):
            continue
        m = _node(nx, ny)
        if not world.passable.get(m) or (nx, ny) in occupied:
            continue
        key = (int(field.get(m, INF)), ny, nx)
        if key < best_key:
            best_key = key
            best_action = action
    return best_action
